keyboard shortcuts
- for docstring https://stackoverflow.com/questions/49042988/quick-docstrings-in-colaboratory

## **Pytorch Fundamentals**

In [ ]:
import torch

In [ ]:
torch.__version__

'2.1.0+cu118'

In [ ]:
!nvidia-smi #nvidia-smi command, which is used to check the GPU usage and performance
#when we get command not found when we run this, it means we r not running on GPU runtime. Change it to GPU from CPU to execute this command

Sun Nov 19 22:06:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P0    27W /  70W |    635MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### **1.Introduction to Tensors**

#### Creating Tensors
- https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar tensor - 0D tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim #rank of the tensor - how many dimensions

0

In [ ]:
scalar.item() #gives the value inside the tensor if it is scalar

7

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
#Vector tensor - 1D tensor
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
vector.item() #throws error as it only works for scalar, not for vector tensor
#Use torch.Tensor.item() to get a Python number from a tensor containing a single value:

RuntimeError: ignored

In [ ]:
import torch
matrix = torch.tensor([[1]]) #shape (1, 1)
matrix.item()

1

In [ ]:
#Matrix = 2D - combination of several 1D vectors
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape #2 rows 2 cols

torch.Size([2, 2])

In [ ]:
MATRIX[1] #second row

tensor([3, 4])

In [ ]:
MATRIX[:, 0] #0th column, all rows

tensor([1, 3])

In [ ]:
#Tensor - 3D, 4D....
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0] #getting the first dimension, we get 2D matrix (3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0, 1] #first dimension 0th index, second dimension second index

tensor([4, 5, 6])

Note: Scalars and vector varaible in lowercase and , matrix and tensor variables in uppercase is the nomenclature

#### **Random Tensors**

`Create random tensors of required distributions like uniform, normal..`

In [ ]:
#creates a random 2d tensor from uniform distribution with 3 rows 4 cols
RANDTENSOR = torch.rand(size=(3, 4))
RANDTENSOR

tensor([[0.8330, 0.4173, 0.7556, 0.7996],
        [0.1591, 0.8125, 0.6666, 0.3599],
        [0.1775, 0.6334, 0.8769, 0.5936]])

In [ ]:
RANDTENSOR.ndim

2

In [ ]:
RANDTENSOR.shape

torch.Size([3, 4])

In [ ]:
RANDTENSOR.size()

torch.Size([3, 4])

In [ ]:
RANDTENSOR = torch.rand(1, 10, 10) #3d tensor
RANDTENSOR

tensor([[[0.5748, 0.6483, 0.1993, 0.7878, 0.3013, 0.0202, 0.2468, 0.6627,
          0.1677, 0.6982],
         [0.8170, 0.6167, 0.5005, 0.5654, 0.7155, 0.6746, 0.9074, 0.7459,
          0.0563, 0.4101],
         [0.7636, 0.1107, 0.9364, 0.4106, 0.9274, 0.8021, 0.2235, 0.4407,
          0.4660, 0.5173],
         [0.1491, 0.8308, 0.8413, 0.2356, 0.6054, 0.3793, 0.2585, 0.9534,
          0.6792, 0.1943],
         [0.2378, 0.6371, 0.7900, 0.0358, 0.6088, 0.5830, 0.2062, 0.3491,
          0.2786, 0.8206],
         [0.0166, 0.9266, 0.1059, 0.9857, 0.7767, 0.8337, 0.7377, 0.4126,
          0.5359, 0.1571],
         [0.7990, 0.5983, 0.0245, 0.9392, 0.6150, 0.9827, 0.7325, 0.6946,
          0.8612, 0.7283],
         [0.3293, 0.2255, 0.2191, 0.2707, 0.0208, 0.5311, 0.9228, 0.6551,
          0.4036, 0.9717],
         [0.0896, 0.7481, 0.2962, 0.9401, 0.5256, 0.7213, 0.9592, 0.7619,
          0.8354, 0.8446],
         [0.0541, 0.0799, 0.9494, 0.6350, 0.1464, 0.4629, 0.2562, 0.4376,
          0.6500,

In [ ]:
RANDTENSOR.ndim

3

In [ ]:
RANDTENSOR = torch.rand(3, 10, 10) #3d tensor
RANDTENSOR

tensor([[[0.0498, 0.7095, 0.8348, 0.1548, 0.4922, 0.5233, 0.8510, 0.3104,
          0.6748, 0.4136],
         [0.5245, 0.8593, 0.8096, 0.7116, 0.2164, 0.8160, 0.9984, 0.4183,
          0.8078, 0.2023],
         [0.4846, 0.2036, 0.2496, 0.9416, 0.5172, 0.3335, 0.3536, 0.2083,
          0.9910, 0.2904],
         [0.1989, 0.1794, 0.6432, 0.8179, 0.4666, 0.1354, 0.5311, 0.7577,
          0.9279, 0.3376],
         [0.7211, 0.1985, 0.0702, 0.0649, 0.3213, 0.8071, 0.2385, 0.0672,
          0.7656, 0.2807],
         [0.8741, 0.9918, 0.7156, 0.9953, 0.9849, 0.4948, 0.2704, 0.1663,
          0.2009, 0.0777],
         [0.3156, 0.1253, 0.4491, 0.0867, 0.1504, 0.2244, 0.3485, 0.8558,
          0.9733, 0.7432],
         [0.7925, 0.5197, 0.4216, 0.8918, 0.9719, 0.3011, 0.1010, 0.9630,
          0.0708, 0.2334],
         [0.5692, 0.5992, 0.1073, 0.1650, 0.0055, 0.5956, 0.6178, 0.7532,
          0.7121, 0.0623],
         [0.7599, 0.8568, 0.2687, 0.9927, 0.3927, 0.4230, 0.4625, 0.9940,
          0.8772,

In [ ]:
RANDTENSOR.ndim

3

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(224, 224, 3) #height, width, channel
random_image_tensor.shape, random_image_tensor.ndim #observe, we can print all in one line

(torch.Size([224, 224, 3]), 3)

In [1]:
import torch
random_tensor = torch.randint(0, 10, size=(4,))
random_tensor

tensor([8, 3, 6, 1])

In [3]:
import torch
random_img_tensor = torch.randint(0, 255, size=(1, 32, 32))
random_img_tensor

tensor([[[192,  51, 100,  ..., 225,  73, 236],
         [159, 128, 170,  ..., 234,  72, 172],
         [ 61, 205, 247,  ..., 116, 199,  35],
         ...,
         [213,  12, 220,  ..., 109,  95, 198],
         [ 21,  15, 121,  ...,  45,  21, 133],
         [143,  19, 233,  ...,  17, 121, 107]]])

#### **Zeros and ones**

In [ ]:
zeros = torch.zeros(3, 4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

#### **Creating a range of tensors and zeros-like, ones_like**

In [ ]:
#torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(start=1, end=10, step=2)

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.arange(start=10, end=1, step=-1)

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [ ]:
#torch.zeros_like, ones_like
original = torch.arange(1, 11)
liketensor = torch.zeros_like(original)
original, original.shape, liketensor, liketensor.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.Size([10]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 torch.Size([10]))

#### **Tensor datatype, device, requires_grad params**

In [ ]:
#even we specify none as dtype, still the dtype is gonna return as float32
#based on input data it has
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor.dtype

torch.float32

In [ ]:
#it will return int eventhough we have given dtype=None, based on i/p data
int_32_tensor = torch.tensor([3, 6, 9], dtype=None)
int_32_tensor.dtype

torch.int64

In [ ]:
#device param, requires_grad params of a tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None, #None, "cpu", "cuda" for gpu, tells what device is your tensor on
                               requires_grad=False)#construct tensor with no autograd history, called leaf tensor, no tracking of tensor
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#dtype param of a tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#convert dtype of a tensor from float32 tensor to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#convert float32 tensor to float 16 using type_as
float_16_tensor_1 = float_32_tensor.type_as(float_16_tensor)
float_16_tensor_1

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#can we multiply float_16 tensor with float_32 tensor?
multipl_16_32 = float_16_tensor_1 * float_32_tensor #yes we could and we get float32
multipl_16_32, multipl_16_32.dtype

(tensor([ 9., 36., 81.]), torch.float32)

```but sometimes tensors of differet datatypes may end up with errors when performing other operations. It is advisable to avoid different datatypes operations```

In [ ]:
#lets try multiply a int tensor and float tensor to see what happens
int_tensor_32 = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor_32 = torch.tensor([1.2, 2., 3.], dtype=torch.float32)
res = int_tensor_32 * float_tensor_32
res, res.dtype #we get float32 as result and multiplication is success

(tensor([1.2000, 4.0000, 9.0000]), torch.float32)

In [ ]:
#lets try division a int tensor and float tensor to see what happens
int_tensor_32 = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor_32 = torch.tensor([1.2, 2., 3.], dtype=torch.float32)
res = int_tensor_32 / float_tensor_32
res, res.dtype #we get float32 as result and division is success

(tensor([0.8333, 1.0000, 1.0000]), torch.float32)

In [ ]:
#lets try division a int32 tensor and float16 tensor to see what happens
int_tensor_32 = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor_16 = torch.tensor([1.2, 2., 3.], dtype=torch.float16)
res = int_tensor_32 / float_tensor_16
res, res.dtype #we get float16 as result and division is success

(tensor([0.8330, 1.0000, 1.0000], dtype=torch.float16), torch.float16)

In [ ]:
#Getting info from tensors - shape, size(), dtype, device
mytensor = torch.rand(3, 4)
mytensor, mytensor.dtype, mytensor.shape, mytensor.size(), mytensor.device
#default dtype is float32, device is cpu if not specified

(tensor([[0.4100, 0.3716, 0.8757, 0.5050],
         [0.1170, 0.0782, 0.4253, 0.7218],
         [0.4660, 0.6588, 0.3866, 0.2083]]),
 torch.float32,
 torch.Size([3, 4]),
 torch.Size([3, 4]),
 device(type='cpu'))

### **Manipulating Tensors(tensor operations)**
- Addition
- Subtraction
- Multiplication(element-wise)
- Division
- Matrix multiplication

In [ ]:
## Addition - adding 10 to a tensor - broadcasting
mytensor = torch.tensor([1, 2, 3])
mytensor + 10

tensor([11, 12, 13])

In [ ]:
## Multiplication - multipying with 10 to a tensor - broadcasting
mytensor = torch.tensor([1, 2, 3])
mytensor = mytensor * 10 #inplace - modifying the tensor
mytensor

tensor([10, 20, 30])

In [ ]:
## Division
mytensor = torch.tensor([1, 2, 3])
mytensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
## Subtraction
mytensor = torch.tensor([1, 2, 3])
mytensor - 10

tensor([-9, -8, -7])

In [ ]:
#sum for 2D or more dimensional tensors
mytensor = torch.tensor([[1, 2, 3]])
torch.sum(mytensor)

tensor(6)

In [ ]:
#sum for 2D or more dimensional tensors
mytensor = torch.tensor([[1, 2, 3]])
torch.sum(mytensor, axis=0)

tensor([1, 2, 3])

In [ ]:
#sum for 2D or more dimensional tensors
mytensor = torch.tensor([[1, 2, 3]])
torch.sum(mytensor, axis=1)

tensor([6])

``Pytorch inbuilt functions for elementwise operations``

But its better to use elementwise operations like add, subtract, multiplication with python opertaors instead of torch built-in functions for better readability

In [ ]:
#multiplication
mytensor = torch.tensor([1, 2, 3])
torch.mul(mytensor, 10)

tensor([10, 20, 30])

In [ ]:
#addition
mytensor = torch.tensor([1, 2, 3])
torch.add(mytensor, 10)

tensor([11, 12, 13])

In [ ]:
#subtract
mytensor = torch.tensor([1, 2, 3])
torch.subtract(mytensor, 10)

tensor([-9, -8, -7])

In [ ]:
#Matrix-multiplication with matmul rules of shapes
#matmul is similar to dot product but we use dot product when we have 1D tensors or when we use loop and it is bit slow compared to matmul
#matmul for 1D, 2D,... vectorized matmul operation without loop
# @ or torch.matmul or torch.mm - matmul, . or torch.dot - dot product

mytensor = torch.tensor([1, 2, 3]) #shape (3,) - single dimension
print(mytensor.shape)
print("Element wise multiplication"+ str(mytensor * mytensor))
print("Matrix multiplication"+ str(torch.matmul(mytensor, mytensor)))
print("Matrix multiplication"+ str(torch.matmul(mytensor, mytensor).shape))
print("Dot product"+ str(torch.dot(mytensor, mytensor)))
print("Dot product"+ str(torch.dot(mytensor, mytensor).shape))
#observe how the one dimension variable gives a scalar value without the dimension.

torch.Size([3])
Element wise multiplicationtensor([1, 4, 9])
Matrix multiplicationtensor(14)
Matrix multiplicationtorch.Size([])
Dot producttensor(14)
Dot producttorch.Size([])


In [ ]:
#But if the matrices are 2D, like (1, 3) shape, then it would give resultant matrix with shape (1, 1)

mytensor = torch.tensor([[1, 2, 3]]) #shape (1, 3) - 2 dimensions
print("Element wise multiplication"+ str(mytensor * mytensor))
print("Matrix multiplication"+ str(torch.matmul(mytensor, mytensor.T))) #matmul 1st cols = 2nd rows, hence transpose
print("Matrix multiplication shape"+ str(torch.matmul(mytensor, mytensor.T).shape))
# print("Dot product"+ str(torch.dot(mytensor, mytensor))) #throws error - 1D tensors expected, but got 2D and 2D tensors

#always perform matmul after reshaping the matrix to atleast 2D

Element wise multiplicationtensor([[1, 4, 9]])
Matrix multiplicationtensor([[14]])
Matrix multiplication shapetorch.Size([1, 1])


In [ ]:
#matrix multiplication of 1D matrix by hand using for loop, also lets time it
%%time
mytensor = torch.tensor([1, 2, 3])
print(len(mytensor)) #3
print(mytensor.shape) #[3,]
value = 0
for i in range(len(mytensor)):
    value += mytensor[i] * mytensor[i]
value

3
torch.Size([3])
CPU times: user 1.85 ms, sys: 0 ns, total: 1.85 ms
Wall time: 2.14 ms


tensor(14)

In [ ]:
#dot product using for loop of 2D tensor =~ matmul
%%time
mytensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(len(mytensor)) #2
print(mytensor.shape) #[2, 3]
value = torch.zeros(2, 2)
for i in range(len(mytensor)):
    for j in range(len(mytensor)):
        # print(mytensor[i])
        # print(mytensor[j])
        value[i][j] = torch.dot(mytensor[i], mytensor[j])
value

2
torch.Size([2, 3])
CPU times: user 1.77 ms, sys: 0 ns, total: 1.77 ms
Wall time: 1.81 ms


tensor([[14., 32.],
        [32., 77.]])

In [ ]:
#matmul
%%time
mytensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(len(mytensor)) #2
print(mytensor.shape) #[2, 3]

#matmul
print(torch.matmul(mytensor, mytensor.T))
print(mytensor @ mytensor.T)
print(torch.mm(mytensor, mytensor.T))

#see the time difference btwn for loop and matmul

2
torch.Size([2, 3])
tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])
CPU times: user 4.3 ms, sys: 0 ns, total: 4.3 ms
Wall time: 6.58 ms


### **Tensor Aggregation**
- Sum
- Max
- Min
- Mean (i.e average)
- Median
- argmax
- argmin

In [ ]:
#max , default axis is max among the whole matrix, gives scalar with collapsed dimension
mytensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(torch.max(mytensor))
print(mytensor.max())

tensor(6)
tensor(6)


In [ ]:
#max , default axis is max among the whole matrix - 1D
mytensor = torch.tensor([1, 2, 3, 4, 5, 6])
print(torch.max(mytensor))
print(mytensor.max())

tensor(6)
tensor(6)


In [ ]:
#max , axis=0
mytensor = torch.tensor([[1, 8, 3], [4, 5, 6]])
print(torch.max(mytensor, axis=0))
print(mytensor.max(0))

torch.return_types.max(
values=tensor([4, 8, 6]),
indices=tensor([1, 0, 1]))
torch.return_types.max(
values=tensor([4, 8, 6]),
indices=tensor([1, 0, 1]))


In [ ]:
#max , axis=1
mytensor = torch.tensor([[3, 2, 3], [4, 5, 6]])
torch.max(mytensor, axis=1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([0, 2]))

In [ ]:
#min, whole matrix
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
torch.min(mytensor)

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])


tensor(1)

In [ ]:
#min, axis=0
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
torch.min(mytensor, axis=0)

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])


torch.return_types.min(
values=tensor([ 1, 11, 21, 31, 41]),
indices=tensor([0, 0, 0, 0, 0]))

In [ ]:
#min, axis=1
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.min(mytensor, axis=1))

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
torch.return_types.min(
values=tensor([ 1, 51]),
indices=tensor([0, 0]))


In [ ]:
#min, axis=0, values
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.min(mytensor, axis=0).values)

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
tensor([ 1, 11, 21, 31, 41])


In [ ]:
#min, axis=1, indices
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.min(mytensor, axis=1).indices)

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
tensor([0, 0])


In [ ]:
#mean, whole matrix, mean only accepts float or complex dtype, not long i.e int64
mytensor = torch.arange(1, 100, 10, dtype=torch.float32) '
#we can also use torch.mean(mytensor.type(torch.float32)) or mytensor.type(torch.float32).mean()
print(mytensor)
print(torch.mean(mytensor))

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])
tensor(46.)


In [ ]:
#mean, axis=0, 1d tensor
mytensor = torch.arange(1, 100, 10, dtype=torch.float32)
print(mytensor)
print(torch.mean(mytensor, axis=0))

tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])
tensor(46.)


In [ ]:
#mean, axis=0, 2d tensor
mytensor = torch.arange(1, 100, 10, dtype=torch.float32).reshape(2, 5)
print(mytensor)
print(torch.mean(mytensor, axis=0))

tensor([[ 1., 11., 21., 31., 41.],
        [51., 61., 71., 81., 91.]])
tensor([26., 36., 46., 56., 66.])


In [ ]:
#mean, axis=1, 2d tensor
mytensor = torch.arange(1, 100, 10, dtype=torch.float32).reshape(2, 5)
print(mytensor)
print(torch.mean(mytensor, axis=1))

tensor([[ 1., 11., 21., 31., 41.],
        [51., 61., 71., 81., 91.]])
tensor([21., 71.])


In [ ]:
#sum
mytensor = torch.arange(1, 100, 10)
print(mytensor)
print(torch.sum(mytensor))

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
tensor(460)


In [ ]:
#sum, axis=0
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.sum(mytensor, axis=0))
#observe how the dimension is collapsed to one dimension

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
tensor([ 52,  72,  92, 112, 132])


In [ ]:
#sum, axis=1
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.sum(mytensor, axis=1))

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
tensor([105, 355])


In [ ]:
#argmin, argmax, whole matrix
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.argmin(mytensor))
print(torch.argmax(mytensor))

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
tensor(0)
tensor(9)


In [ ]:
#argmin, argmax, axis=0
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.argmin(mytensor, axis=0))
print(torch.argmax(mytensor, axis=0))

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
tensor([0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1])


In [ ]:
#argmin, argmax, axis=1
mytensor = torch.arange(1, 100, 10).reshape(2, 5)
print(mytensor)
print(torch.argmin(mytensor, axis=1))
print(torch.argmax(mytensor, axis=1))

tensor([[ 1, 11, 21, 31, 41],
        [51, 61, 71, 81, 91]])
tensor([0, 0])
tensor([4, 4])


### **Tensor Reshaping, Viewing, stacking, squeezing, unsqueezing, Permuting**

In simple terms, all the below are used to manipulate the input tensors shape in required dimension
- reshape - reshapes an input tensor to a defined shape
- view - return a view of an input tensor of certain shape but keep the memory as the original tensor, share the same memory as original tensor
- stack (stack with axis, vstack, hstack) - combine/contanate multiple tensors on top of each other(vstack) or side by side(hstack)
- squeeze - removes all `1` dimensions from a tensor
- unsqueeze - add a `1` dimension to a target tensor
- permute - return a view of the input with dimensions permuted(swapped) in a certain specified way

In [ ]:
mytensor = torch.arange(1., 10.)
mytensor, mytensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#reshape - adding extra axis along dimension 0
#make sure the dimensions of reshaped tensor should match with the original tensor
#multiplication(no. of elements) of shape should result in original tensor shape

mytensor = torch.arange(1., 10.) #shape (9,)
mytensor_reshaped = mytensor.reshape(1, 9)
mytensor_reshaped, mytensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#reshape - adding new dimension along dimension 1
mytensor = torch.arange(1., 10.)
mytensor_reshaped = mytensor.reshape(9, 1)
mytensor_reshaped, mytensor_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#reshape - so that no. of elements of original tensor and reshaped tensor match
mytensor = torch.arange(1., 10.) #(9,)
mytensor_reshaped = mytensor.reshape(3, 3)
mytensor_reshaped, mytensor_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
#reshape - to 3D
mytensor = torch.arange(1., 10.)
mytensor_reshaped = mytensor.reshape(3, 3, 1) # creates 3 (3,1) matrices
mytensor_reshaped, mytensor_reshaped.shape

(tensor([[[1.],
          [2.],
          [3.]],
 
         [[4.],
          [5.],
          [6.]],
 
         [[7.],
          [8.],
          [9.]]]),
 torch.Size([3, 3, 1]))

In [ ]:
#reshape - to 3D
mytensor = torch.arange(1., 10.)
mytensor_reshaped = mytensor.reshape(9, 1, 1)
mytensor_reshaped, mytensor_reshaped.shape

(tensor([[[1.]],
 
         [[2.]],
 
         [[3.]],
 
         [[4.]],
 
         [[5.]],
 
         [[6.]],
 
         [[7.]],
 
         [[8.]],
 
         [[9.]]]),
 torch.Size([9, 1, 1]))

In [ ]:
#reshape - throws error if no. of elements in the reshape shape doesnt match with original tensor elements
#here we are trying to put 9 elements in 10 elements tensor - so it throws error
mytensor = torch.arange(1., 10.) #9 elements
mytensor_reshaped = mytensor.reshape(10, 1)
#mytensor_reshaped = mytensor.reshape(7, 1) #also throws error as we are trying to squeeze 9 elements in 7 element tensor
mytensor_reshaped, mytensor_reshaped.shape

RuntimeError: ignored

In [ ]:
#view
mytensor = torch.arange(1., 10.) #shape (9,)
z = mytensor.view(1, 9) #changes the view of mytensor to (1, 9) but doesnt alter the shape of original mytensor here. It shows the view of original tensor in specified shape
z, z.shape, mytensor.shape

#If you observe, view is similar to reshape, but the only the difference is,
#view variable z shares the memory with the original tensor mytensor here
#z is just a different view of mytensor, it shares the same memory as mytensor,
#it wont create new memory for z unlike reshape that creates new memory instance
#if you change something in z or mytensor, the other tensor value also changes

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 torch.Size([9]))

In [ ]:
#Changing z(i.e view of original tensor) changes also the original tensor
#cuz they share the same memory, z is just a view of original tensor

#shape (9,)
z = mytensor.view(1, 9) #changes the view of mytensor to (1, 9)

#lets change z(may be the modify one element in z) and observe it changes mytensor too
z[:, 0] = 11
z, z.shape, mytensor, mytensor.shape
#modified the element in both, the shape of both doesnt get altered though

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 torch.Size([1, 9]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 torch.Size([9]))

In [ ]:
#stack or vstack
#stack on top of each other like vstack - note shapes of stacking matrices should match
#Note: stacking 1D vectors creates 2D matrix - it is creating a new dimension in the specfied axis

x = torch.arange(1., 10.) #shape(9,)
print(x)
y = torch.arange(11., 20.) #shape(9,)
print(y)

x_stacked = torch.stack([x, y], axis=0) #vstack
x_stacked, x_stacked.shape

#think of it as it contantenating the dimension on specified axis position

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.])


(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [11., 12., 13., 14., 15., 16., 17., 18., 19.]]),
 torch.Size([2, 9]))

In [ ]:
#stack or hstack
#stack side by side like hstack - 1D vectors, stacking results in 2D matrix

x = torch.arange(1., 10.) #shape(9,)
print(x)
y = torch.arange(11., 20.) ##shape(9,)
print(y)

x_stacked = torch.stack([x, y], axis=1) #hstack
x_stacked, x_stacked.shape

#observe how each 1D vector is changed as column vector
#think of it as it contantenating the dimension on specified axis position

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([11., 12., 13., 14., 15., 16., 17., 18., 19.])


(tensor([[ 1., 11.],
         [ 2., 12.],
         [ 3., 13.],
         [ 4., 14.],
         [ 5., 15.],
         [ 6., 16.],
         [ 7., 17.],
         [ 8., 18.],
         [ 9., 19.]]),
 torch.Size([9, 2]))

In [ ]:
#vstack on top of each other like vstack for 2D matrices - results in 3D matrix

x = torch.arange(1., 10.). reshape(1, 9)
print(x)
y = torch.arange(11., 20.).reshape(1, 9)
print(y)

x_stacked = torch.stack([x, y], dim=0) #vstack
x_stacked, x_stacked.shape

#observe the shape - it is 2 - (1,9) matrices i.e a 3d Matrix
#concatenates along the specified axis, at axis position 0, it concatenates both the matrices (2, 1, 9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[11., 12., 13., 14., 15., 16., 17., 18., 19.]])


(tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]],
 
         [[11., 12., 13., 14., 15., 16., 17., 18., 19.]]]),
 torch.Size([2, 1, 9]))

In [ ]:
#hstack side by side like hstack for 2D matrices - results in 3D matrix

x = torch.arange(1., 10.). reshape(1, 9)
print(x)
y = torch.arange(11., 20.).reshape(1, 9)
print(y)

x_stacked = torch.stack([x, y], axis=1) #hstack
x_stacked, x_stacked.shape

#observe the shape, it is 1 - (2, 9) matrices
#concatenates along the specified axis, at axis position 1, it concatenates both the matrices (1, 2, 9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[11., 12., 13., 14., 15., 16., 17., 18., 19.]])


(tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
          [11., 12., 13., 14., 15., 16., 17., 18., 19.]]]),
 torch.Size([1, 2, 9]))

In [ ]:
#many stacks of 1D vstack  - contanates on specified axis and create a 2D matrix
x = torch.arange(1., 10.) #(9,)
x_stacked = torch.stack([x, x, x, x], dim=0) #vstack - results in (4, 9)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
#many stacks of 1D hstack
x = torch.arange(1., 10.) #(9,)
x_stacked = torch.stack([x, x, x, x], dim=1) #hstack - results in (9, 4)
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
#many stacks of 2D - vstack - creates 3D matrix
x = torch.arange(1., 10.). reshape(1, 9)
x_stacked = torch.stack([x, x, x, x], dim=0) #hstack - results in (4, 1, 9)
x_stacked, x_stacked.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[1., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([4, 1, 9]))

In [ ]:
#many stacks of 2D - hstack
x = torch.arange(1., 10.). reshape(1, 9)
x_stacked = torch.stack([x, x, x, x], dim=1) #hstack - results in (1, 4, 9)
x_stacked, x_stacked.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.],
          [1., 2., 3., 4., 5., 6., 7., 8., 9.],
          [1., 2., 3., 4., 5., 6., 7., 8., 9.],
          [1., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([1, 4, 9]))

In [ ]:
#cat is similar to stack but wont create a new dimension in the specified axis
#Concatenates the given sequence of tensors in the given dimension.
#All tensors must either have the same shape (except in the concatenating dimension) or be empty.
#torch.cat() can be seen as an inverse operation for torch.split() and torch.chunk().
#While torch.stack() concatenates the given sequence along a new dimension.
import torch
x = torch.arange(6).reshape(2, 3)
myconcat = torch.cat([x, x]) #default is axis=0, vertical concat
x, x.size(), myconcat, myconcat.shape

#observe how they are concstenated in the 0th dimension without creating new axis, also 2d concats results in 2d concats

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [0, 1, 2],
         [3, 4, 5]]),
 torch.Size([4, 3]))

In [ ]:
#torch.cat() with axis=1, horizontal concat
import torch
x = torch.arange(6).reshape(2, 3)
myconcat = torch.cat([x, x, x], axis=1) #default is axis=0
x, x.size(), myconcat, myconcat.shape #results in (2, 9)

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]),
 tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
         [3, 4, 5, 3, 4, 5, 3, 4, 5]]),
 torch.Size([2, 9]))

In [ ]:
#torch.cat() with axis=1, horizontal concat
import torch
x = torch.arange(6).reshape(2, 3)
myconcat = torch.cat([x, x, x], axis=1) #default is axis=0
#les change original tensor and see how it effects the concatenated tensor - it wont affect as they dont share memory
x[0, 1] = 9 #wont change the concatenated tensor
x, x.size(), myconcat, myconcat.shape

(tensor([[0, 9, 2],
         [3, 4, 5]]),
 torch.Size([2, 3]),
 tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
         [3, 4, 5, 3, 4, 5, 3, 4, 5]]),
 torch.Size([2, 9]))

In [ ]:
#torch.split(tensor, split_size_or_sections, dim=0) opposite of concatenation
#Splits the tensor into chunks. Each chunk is a view of the original tensor.
#If split_size_or_sections is an integer type, then tensor will be split into equally sized chunks (if possible).
#Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by split_size.
#If split_size_or_sections is a list, then tensor will be split into len(split_size_or_sections) chunks with sizes in dim according to split_size_or_sections.
#returns tuple of splits
a = torch.arange(10).reshape(5, 2)
z = torch.split(a, 3, dim=0) #returns splits by using dim=0/split size = 5/3 = 1 (3, 2) and remaining (2, 2)
a, a.shape, z, type(z), len(z) #z is view of a

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]),
 (tensor([[0, 1],
          [2, 3],
          [4, 5]]),
  tensor([[6, 7],
          [8, 9]])),
 tuple,
 2)

In [ ]:
#split with 2 as split size along dim 0
a = torch.arange(10).reshape(5, 2)
z = torch.split(a, 2, dim=0) #returns splits by using dim=0/split size = 5/2 = 2 (2, 2) and remaining (1, 2)
a, a.shape, z, type(z), len(z)

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]),
 (tensor([[0, 1],
          [2, 3]]),
  tensor([[4, 5],
          [6, 7]]),
  tensor([[8, 9]])),
 tuple,
 3)

In [ ]:
#split with 2 as split size along dim 1
a = torch.arange(10).reshape(5, 2)
z = torch.split(a, 2, dim=1) #returns splits by using dim=1/split size = 2/2 = 1 (5, 2)
a, a.shape, z, type(z), len(z)

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]),
 (tensor([[0, 1],
          [2, 3],
          [4, 5],
          [6, 7],
          [8, 9]]),),
 tuple,
 1)

In [ ]:
#split with list
a = torch.arange(10).reshape(5, 2)
y = torch.split(a, [4, 1], dim=0) #note t he split size list should sum up to specified dim, otherwise split throws error
a, a.shape, y, type(y), len(y) #number of splits = len(splits), each split is of size specifies

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]),
 (tensor([[0, 1],
          [2, 3],
          [4, 5],
          [6, 7]]),
  tensor([[8, 9]])),
 tuple,
 2)

In [ ]:
#split with list
a = torch.arange(10).reshape(5, 2)
y = torch.split(a, [1, 1, 3], dim=0) #note t he split size list should sum up to specified dim, otherwise split throws error
a, a.shape, y, type(y), len(y) #number of splits = len(splits), each split is of size specifies

(tensor([[0, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 torch.Size([5, 2]),
 (tensor([[0, 1]]),
  tensor([[2, 3]]),
  tensor([[4, 5],
          [6, 7],
          [8, 9]])),
 tuple,
 3)

In [ ]:
#Squeeze - removes all single dimensions
x = torch.rand(1, 9) #2D rand matrix - (1, 9) shape
x_squeezed = torch.squeeze(x) #removes all single(i.e 1) dimensions
x_squeezed, x_squeezed.shape

(tensor([0.5722, 0.3600, 0.3053, 0.8419, 0.0156, 0.9315, 0.6137, 0.6469, 0.8203]),
 torch.Size([9]))

In [ ]:
#Squeeze
x = torch.rand(3, 1, 9)
x_squeezed = torch.squeeze(x) #removes all single dimensions
x_squeezed, x_squeezed.shape

(tensor([[0.9409, 0.6097, 0.7303, 0.7773, 0.4734, 0.5287, 0.5762, 0.1418, 0.0549],
         [0.3758, 0.8665, 0.5548, 0.3031, 0.1574, 0.1892, 0.7647, 0.3592, 0.3243],
         [0.8961, 0.2962, 0.5720, 0.7616, 0.5108, 0.6592, 0.4729, 0.0958, 0.2991]]),
 torch.Size([3, 9]))

In [ ]:
#Squeeze
x = torch.rand(1, 1, 9)
x_squeezed = torch.squeeze(x) #removes all single dimensions
x_squeezed, x_squeezed.shape

(tensor([0.0827, 0.4191, 0.7804, 0.9521, 0.0110, 0.4553, 0.7805, 0.7213, 0.2481]),
 torch.Size([9]))

In [ ]:
#squeeze with axis=0
x = torch.rand(1, 1, 9)
x_squeezed = torch.squeeze(x, axis=0) #removes single dimensions in the specified axis
x_squeezed, x_squeezed.shape

(tensor([[0.9369, 0.6349, 0.0922, 0.0212, 0.2508, 0.9257, 0.3828, 0.3973, 0.1609]]),
 torch.Size([1, 9]))

In [ ]:
#squeeze with axis=1
x = torch.rand(1, 1, 9)
x_squeezed = torch.squeeze(x, axis=1) #removes single dimensions in the specified axis
x_squeezed, x_squeezed.shape

(tensor([[0.9161, 0.1603, 0.4227, 0.1836, 0.5709, 0.7000, 0.7228, 0.2823, 0.4317]]),
 torch.Size([1, 9]))

In [ ]:
#squeeze with axis=2, if there is no single dim in the specified axis, then it doesnt change anything
x = torch.rand(1, 1, 9)
x_squeezed = torch.squeeze(x, axis=2)
x_squeezed, x_squeezed.shape

(tensor([[[0.5244, 0.0485, 0.3735, 0.2527, 0.5644, 0.1040, 0.8604, 0.8302,
           0.9635]]]),
 torch.Size([1, 1, 9]))

In [ ]:
#unsqueeze() - adds a single dimension to the target tensor at the specific dim
x = torch.arange(1., 10.) #(9,)
print(x.shape)
x_unsqueezed = torch.unsqueeze(x, dim=0)
x_unsqueezed, x_unsqueezed.shape

torch.Size([9])


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#unsqueeze() - adds a single dimension to the target tensor at the specific dim
x = torch.arange(1., 10.) #(9,)
print(x.shape)
x_unsqueezed = torch.unsqueeze(x, dim=1)
x_unsqueezed, x_unsqueezed.shape

torch.Size([9])


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#unsqueeze() - adds a single dimension to the target tensor at the specific dim
x = torch.rand(2, 3) #2D matrix shape (2, 3)
print(x.shape)
x_unsqueezed = torch.unsqueeze(x, dim=1) #adds new dim at axis=1 position
x_unsqueezed, x_unsqueezed.shape

torch.Size([2, 3])


(tensor([[[0.9187, 0.7700, 0.4104]],
 
         [[0.6246, 0.7881, 0.8985]]]),
 torch.Size([2, 1, 3]))

In [ ]:
#permute() - rearranges/swaps the dimensions of a target tensor with the specified dimensions
#this returns the view of a original input tensor with the specified dimensions - shared memory with original tensor
#Note:number of dimensions should match with the original tensor
#permute is used specially with images

x = torch.rand(2, 3) #2D shape - (2, 3), axis=0 is 2, axis=1 is 3
print(x.shape)
print(x.ndim)
x_permuted = torch.permute(x, (1, 0)) #rearranges axis 0 with axis 1 - resultant shape is (3, 2)
x_permuted, x_permuted.shape

torch.Size([2, 3])
2


(tensor([[0.9214, 0.1027],
         [0.1448, 0.3962],
         [0.1083, 0.5010]]),
 torch.Size([3, 2]))

In [ ]:
x = torch.rand(2, 3, 5) #axis=0 is 2, axis=1 is 3, axis=2 is 5
print(x.shape)
print(x.ndim)
x_permuted = torch.permute(x, (2, 0, 1)) #rearranges and the result will have shape (5, 2, 3)
x_permuted, x_permuted.size()

torch.Size([2, 3, 5])
3


(tensor([[[0.5971, 0.9160, 0.0104],
          [0.4019, 0.6722, 0.9785]],
 
         [[0.2735, 0.6564, 0.9202],
          [0.5873, 0.5792, 0.1812]],
 
         [[0.9070, 0.4338, 0.5861],
          [0.7571, 0.2866, 0.4753]],
 
         [[0.4250, 0.2546, 0.2385],
          [0.1199, 0.7644, 0.7839]],
 
         [[0.9421, 0.6633, 0.8925],
          [0.4988, 0.8506, 0.5455]]]),
 torch.Size([5, 2, 3]))

In [ ]:
#permute the image of (h, w, c) to (c, h, w)
img_original = torch.rand(size=(224, 224, 3))
img_permuted = img_original.permute(2, 1, 0)
img_permuted.size(), img_original.size()

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

### **Tensor Indexing**
    Indexing in pytorch is similary to numpy indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#access the first element in 3dim matrix - returns 2D matrix in first index
x = torch.arange(1, 10).reshape(1, 3, 3)
x[0], x[0].size() #index on the first dim, dim=0

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
#index on the middle bracket, second dim, dim=1
x = torch.arange(1, 10).reshape(1, 3, 3)
x[0][0], x[0, 0], x[0][0].size() #returns 0th index 2D matrix's of dim (3, 3), 0th row in (3, 3)
#observe we get 1D when we index 2 axis in a 3D matrix

(tensor([1, 2, 3]), tensor([1, 2, 3]), torch.Size([3]))

In [ ]:
#index on the inner bracket i.e last dim, dim=2
x = torch.arange(1, 10).reshape(1, 3, 3)
x[0][0][0], x[0, 0, 0], x[0][0][0].size()

(tensor(1), tensor(1), torch.Size([]))

In [ ]:
#index on the inner bracket i.e last dim, dim=2
x = torch.arange(1, 10).reshape(1, 3, 3)
x[0][0][1], x[0, 0, 1], x[0][0][1].size()

(tensor(2), tensor(2), torch.Size([]))

In [ ]:
#index on the inner bracket i.e last dim, dim=2 along with middle bracket dim=1 with index 1
x = torch.arange(1, 10).reshape(1, 3, 3)
x[0][1][1], x[0, 1, 1], x[0][1][1].size()
#observe we got scalar here as we are indexing on all the axis

(tensor(5), tensor(5), torch.Size([]))

In [ ]:
#index with first bracket=1
x = torch.arange(1, 10).reshape(1, 3, 3)
x[1][1][1], x[1, 1, 1], x[1][1][1].size() #throws error as we have only 1 element in dim 0 - (1, 3, 3) => only 1 (3,3) matrix

IndexError: ignored

In [ ]:
#index on the inner bracket i.e last dim, dim=2
x = torch.arange(1, 10).reshape(1, 3, 3)
x[0][1][1], x[0, 1, 1], x[0][1][1].size()

(tensor(5), tensor(5), torch.Size([]))

In [ ]:
#: - get all the elements in 0th and 1st dim but only index 1 of second dim
x = torch.arange(1, 10).reshape(1, 3, 3)
x[:, :, 1], x[:, :, 1].size() #returns 2D matrix of remaining dimensions shape(where we used :) instead of specified dim
# x[:][:][1], x[:][:][1].size() #this wont work, use only the above representation when using :

(tensor([[2, 5, 8]]), torch.Size([1, 3]))

In [ ]:
#: - get all the elements in 0th and 2nd dim but only index 1 of first dim
x = torch.arange(1, 19).reshape(3, 2, 3)
print(x)
x[:, 1, :], x[:, 1, :].size() #returns 2D matrix of remaning dimensions shape(where we used :) instead of specified dim

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])


(tensor([[ 4,  5,  6],
         [10, 11, 12],
         [16, 17, 18]]),
 torch.Size([3, 3]))

In [ ]:
#: - get all the elements in 0th but only index 1 of second dim, 1 of third dim
x = torch.arange(1, 19).reshape(3, 2, 3)
print(x)
x[:, 1, 1], x[:, 1, 1].size() #returns 1D matrix of remaining dimensions shape(where we used :) instead of specified dim

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])


(tensor([ 5, 11, 17]), torch.Size([3]))

### **Pytorch tensors and numpy**
- torch.from_numpy(ndarray) - Data in numpy array to Pytorch tensor - Changes in the NumPy array reflects in the tensor.
- torch.Tensor.numpy() - Pytorch tensor to numpy array - shares memory. A change in the tensor reflects in the NumPy array.

In [ ]:
#convert numpy array to torch tensor
import numpy as np
myarray = np.random.rand(2, 3)
print(myarray.shape)
print(type(myarray))

#converting to tensor
mytensor = torch.from_numpy(myarray)
print(mytensor) #observe the dtype is float64, cux the default dtype for np is float64, hence conversion is also float64
print(mytensor.shape)
print(type(mytensor))

#note but for torch,usually the default dtype is float32

(2, 3)
<class 'numpy.ndarray'>
tensor([[0.8800, 0.5006, 0.8982],
        [0.5433, 0.8242, 0.1111]], dtype=torch.float64)
torch.Size([2, 3])
<class 'torch.Tensor'>


In [18]:
#change in numpy array reflect in tensor
import numpy as np
myarray = np.ones((2, 3))

#converting to tensor
mytensor = torch.from_numpy(myarray)

print(mytensor)
print(myarray)

#change numpy array
myarray[:, 1] = 5
print(mytensor)
print(myarray)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 5., 1.],
        [1., 5., 1.]], dtype=torch.float64)
[[1. 5. 1.]
 [1. 5. 1.]]


In [10]:
#convert torch tensor to numpy array
mytensor = torch.rand(2, 3)
print(type(mytensor))

#converting to numpy
myarray = torch.Tensor(mytensor).numpy() #myarray = mytensor.numpy() also works
print(myarray)
print(myarray.dtype) #float32, cuz torch default dtype is float32
print(myarray.shape)
print(type(myarray))

<class 'torch.Tensor'>
[[0.19944525 0.53114545 0.21373248]
 [0.3263812  0.1673665  0.24456131]]
float32
(2, 3)
<class 'numpy.ndarray'>


In [14]:
#chnage in tensor chnages numpy array as they share memory when using .numpy()
mytensor = torch.ones(2, 3)

#converting to numpy
myarray = mytensor.numpy() #myarray = mytensor.numpy() also works
print(mytensor)
print(myarray)

#modify the tensor
mytensor[:, 1] = 3
mytensor, myarray

tensor([[1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]]


(tensor([[1., 3., 1.],
         [1., 3., 1.]]),
 array([[1., 3., 1.],
        [1., 3., 1.]], dtype=float32))

In [ ]:
#what will happen, if we change the numpy array, then, what happens to tensor that is constructed from ndarray? - it wont chnage as they dont share memory like view
import numpy as np
myarray = np.arange(1, 10).reshape(3, 3)
print(myarray)

#converting to tensor
mytensor = torch.from_numpy(myarray).type(torch.float32) #observe we can also change the dtype to float32 where as deafult from np is float64
print(mytensor)

#lets modify the  myarray and see whther it effects the mytensor
myarray = myarray + 10
print("After")
print(myarray)
print(mytensor) #doesnt alter, it holds true for other conversion too, numpy to tensor conversion


[[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
After
[[11 12 13]
 [14 15 16]
 [17 18 19]]
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


### **Pytorch Reproducibility**

Using seed in random

More info: https://pytorch.org/docs/stable/notes/randomness.html

In [ ]:
#without seed
import torch

randtensor_1 = torch.rand(3, 4)
randtensor_2 = torch.rand(3, 4)
randtensor_1, randtensor_2, randtensor_1 == randtensor_2

(tensor([[0.3253, 0.0812, 0.4807, 0.9843],
         [0.0696, 0.6656, 0.9906, 0.1498],
         [0.8047, 0.8190, 0.4115, 0.1681]]),
 tensor([[0.5678, 0.5044, 0.6207, 0.7248],
         [0.9813, 0.7951, 0.2166, 0.7590],
         [0.2051, 0.7535, 0.0236, 0.7730]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
#with seed - reproducible tensors i.e it results in same tensor for every execution
#make sure to keep the same seed before every random tensor of same shape, other wise u ll get different random tensor of where we didnt add seed
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randtensor_1 = torch.rand(3, 4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randtensor_2 = torch.rand(3, 4)

randtensor_1, randtensor_2, randtensor_1 == randtensor_2

#to get same tensor for both variables, we need to use same seed before both tensors
#but if you want diffrnt tensor but they should be generated similar for every execution, then oone seed is enough

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
#with seed - reproduceable tensors i.e it results in same tensor for every execution, but they bpth wont be same like above
#this is th example where we get rand tensors as we didnt place seed before the second tensor
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
randtensor_1 = torch.rand(3, 4)

randtensor_2 = torch.rand(3, 4)

randtensor_1, randtensor_2, randtensor_1 == randtensor_2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

### **Running tensors and pytorch objects on GPUs(for faster computation)**

https://pytorch.org/docs/stable/notes/cuda.html

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes for faster computation

- Options to use free GPU is via google colab or colab pro or colab pro+
- Use your own GPU which takes littlebit of set up and investment of purchasing a GPU
- Use Cloud computing - GCP - Google Cloud Platform, Amazon AWS, Microsoft Azure - these services allow you to rent computers on the cloud and access them

For 2, 3, refer to pytorch setup documentation

In [ ]:
!nvidia-smi #make sure you change the runtime to GPU in colab for it return the GPU details

Sun Nov 19 22:05:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P0    27W /  70W |    635MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
### check for GPU access with pytorch
import torch
torch.cuda.is_available()#cuda is nvidia paralled computing interface that allows us to use GPUs

True

### **Setting up Device Agnostic code**

In [ ]:
#Setup device agnostic code by setting the device variable
# see best practices section - Device-agnostic code - https://pytorch.org/docs/stable/notes/cuda.html
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device #we can use any variable here. device is used for readability, we use this variable later in the code


'cuda'

In [ ]:
#count the number of GPUs
import torch
torch.cuda.device_count()

#https://pytorch.org/docs/stable/notes/cuda.html - to understand on how to run different operations on multiple GPUs, see best practices section - Device-agnostic code

1

### **Setting up device agnostic code and putting tensors on and off the GPU**

In [ ]:
# Putting tensors and models on GPU - cuz we want our tensors/model on GPU bcuz with GPU, we can achieve faster computation

#creates tensor variable on CPU device and cpu is the default device
mytensor = torch.tensor([1, 2, 3], device="cpu")
print(mytensor, mytensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor variable to GPU if available, else keep it in cpu. For this, we can use our device variable
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
mytensor = torch.tensor([1, 2, 3]) #lets create a tensor that was initially on cpu

#move the tensor to gpu or lets just say the target device
tensor_on_gpu = mytensor.to(device) #moves to gpu if exists else keep it in cpu

print(tensor_on_gpu, tensor_on_gpu.device)

#Here cuda:0, 0 represents the index of our GPU. As we have only one GPU, we get one in the 0th index
#if we have more GPUs, then it will give the index of the GPU where the tensor is moved

tensor([1, 2, 3], device='cuda:0') cuda:0


### **Moving tensors back to CPU**

- FOr eg, Numpy arrays only work on CPUs, so we would need to move our tensors back to cpu before changing it to numpy array

In [ ]:
#convert the gpu tensor to cpu using tensor.cpu() and then use tensor.numpy() for converting to numpy array.
#using directly tensor_on_gpu.numpy() throws error

import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
mytensor = torch.tensor([1, 2, 3])
tensor_on_gpu = mytensor.to(device) #moves to gpu if exists else keep it in cpu

#convert back to cpu
tensor_on_cpu = tensor_on_gpu.cpu()
print(tensor_on_cpu, tensor_on_cpu.device)
tensor_to_numpy = tensor_on_cpu.numpy() #before using numpy operations or even matplotlib, you need to convert gpu tensors to cpu first using .cpu()
tensor_to_numpy


tensor([1, 2, 3]) cpu


array([1, 2, 3])

### Exercises and Extra Cirriculum of Fundamentals from learnpytorch.io

https://www.learnpytorch.io/00_pytorch_fundamentals/

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb

#### Exercise - https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb


In [ ]:
#2. Create a random tensor with shape (7, 7)
import torch
randtensor = torch.rand(7, 7)
randtensor

tensor([[0.8493, 0.3823, 0.4027, 0.9836, 0.1611, 0.3413, 0.2639],
        [0.1290, 0.3436, 0.3251, 0.1980, 0.1889, 0.8084, 0.8720],
        [0.3975, 0.6625, 0.5379, 0.0508, 0.9605, 0.0503, 0.1468],
        [0.3227, 0.2875, 0.9458, 0.8068, 0.1479, 0.0077, 0.4584],
        [0.4240, 0.1123, 0.9784, 0.1217, 0.2616, 0.4602, 0.2381],
        [0.5125, 0.2519, 0.5665, 0.6018, 0.7618, 0.4739, 0.5245],
        [0.0083, 0.7461, 0.2699, 0.3545, 0.3179, 0.9277, 0.5126]])

In [ ]:
#3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
#(hint: you may have to transpose the second tensor).
randtensor2 = torch.rand(1, 7)
mulres = torch.matmul(randtensor, randtensor2.T)
mulres

tensor([[2.1492],
        [1.2923],
        [0.9560],
        [1.4096],
        [1.1286],
        [1.6751],
        [1.5290]])

In [ ]:
#4. Set the random seed to 0 and do 2 & 3 over again.
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
randtensor1 = torch.rand(7, 7)
randtensor2 = torch.rand(1, 7)

matmulres = torch.mm(randtensor1, randtensor2.T)
matmulres, matmulres.size()

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
#5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
#(hint: you'll need to look into the documentation for torch.cuda for this one)
#If there is, set the GPU random seed to 1234.
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
torch.cuda.manual_seed_all(RANDOM_SEED)
randtensor1 = torch.rand(7, 7).cuda()

torch.manual_seed(RANDOM_SEED)
torch.cuda.manual_seed_all(RANDOM_SEED)
randtensor2 = torch.rand(1, 7).cuda()

matmulres = torch.mm(randtensor1, randtensor2.T)
randtensor1.device, randtensor2.device, matmulres, matmulres.device, matmulres.size()


(device(type='cuda', index=0),
 device(type='cuda', index=0),
 tensor([[0.8613],
         [1.2761],
         [1.1540],
         [1.0134],
         [0.6783],
         [1.1122],
         [0.7266]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.Size([7, 1]))

In [ ]:
#6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
#Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
#The output should be something like:
# Device: cuda
# (tensor([[0.0290, 0.4019, 0.2598],
#          [0.3666, 0.0583, 0.7006]], device='cuda:0'),
#  tensor([[0.0518, 0.4681, 0.6738],
#          [0.3315, 0.7837, 0.5631]], device='cuda:0'))
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
randtensor1 = torch.rand(2, 3)
randtensor2 = torch.rand(2, 3)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
randtensor1 = randtensor1.to(device) #we need to reassign to reflect the tensor on GPU
randtensor2 = randtensor2.to(device)

randtensor1, randtensor1.device, randtensor2, randtensor2.device

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 device(type='cuda', index=0),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'),
 device(type='cuda', index=0))

In [ ]:
#7. Perform a matrix multiplication on the tensors you created in 6
#(again, you may have to adjust the shapes of one of the tensors).
# The output should look like:

# (tensor([[0.3647, 0.4709],
#          [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
randtensor1 = torch.rand(2, 3)
randtensor2 = torch.rand(2, 3)
device = "cuda" if torch.cuda.is_available() else "cpu"
randtensor1 = randtensor1.to(device) #we need to reassign to reflect the tensor on GPU
randtensor2 = randtensor2.to(device)
matmulres = randtensor1 @ randtensor2.T

matmulres, matmulres.device, matmulres.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.Size([2, 2]))

In [ ]:
#8. Find the maximum and minimum values of the output of 7.
import torch
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
randtensor1 = torch.rand(2, 3)
randtensor2 = torch.rand(2, 3)
device = "cuda" if torch.cuda.is_available() else "cpu"
randtensor1 = randtensor1.to(device) #we need to reassign to reflect the tensor on GPU
randtensor2 = randtensor2.to(device)
matmulres = randtensor1 @ randtensor2.T

matmulres.max(), torch.min(matmulres)

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [ ]:
#9. Find the maximum and minimum index values of the output of 7.
import torch
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
randtensor1 = torch.rand(2, 3)
randtensor2 = torch.rand(2, 3)
device = "cuda" if torch.cuda.is_available() else "cpu"
randtensor1 = randtensor1.to(device) #we need to reassign to reflect the tensor on GPU
randtensor2 = randtensor2.to(device)
matmulres = randtensor1 @ randtensor2.T

matmulres.argmax(), torch.argmin(matmulres)

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [ ]:
#10. Make a random tensor with shape (1, 1, 1, 10) and
#then create a new tensor with all the 1 dimensions removed to be left
#with a tensor of shape (10). Set the seed to 7 when you create it and
#print out the first tensor and it's shape as well as the second tensor and it's shape.
import torch
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
mytensor1 = torch.rand(1, 1, 1, 10)
mytensor2 = mytensor1.squeeze()

mytensor1, mytensor1.shape, mytensor2, mytensor2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [5]:
#matmul with out param
import torch

# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
tensor = torch.ones(4, 4)
tensor[:,1] = 0
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
tensor, y1, y2, y3

(tensor([[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]),
 tensor([[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]))

In [4]:
#element wise multiplication with out param
# This computes the element-wise product. z1, z2, z3 will have the same value
tensor = torch.ones(4, 4)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
tensor, z1, z2, z3

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

#### Inplace operations

0 Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

Note: In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.


In [6]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [7]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(f"{tensor} \n")
tensor.copy_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [9]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(f"{tensor} \n")
tensor.t_() #inplace transpose
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Extra Cirriculum
- https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html
- https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html