<img src="https://drive.google.com/uc?id=1jCgrCzjYNz4efC-GEQ1zB9pfDa1b3A2o"/>

image url

https://drive.google.com/uc?id=1jCgrCzjYNz4efC-GEQ1zB9pfDa1b3A2o

ctrl - for function autofill or docstring(just like tab , shift+tab in jupyter)

cntrl + space - for arguments autofill

cntrl+ M + m - code cell to markdown

cntrl + M + Y - Markdown to code

We can also use PIL. Make sure you mount the drive before displaying/accessing the images from drive

```
from PIL import Image
from google.colab import drive

drive.mount('/content/drive') #mount drive if not mounted to access the drive

eff_b0 = Image.open("/content/drive/MyDrive/Colab Notebooks/Pytorch/images/06-effnet-b0-feature-extractor.png")

eff_b0
```


### **Tensors Shapes**

<img src="https://drive.google.com/uc?id=1wyNMOG6bzG0baG45AkNLEmeoe9lPsSKf" />

## **Creating Tensors**
- Using tf.constant()
  - Zero dim tensor
  - 1D tensor
  - 2D tensor
  - 3D tensor
  - 4D tensor

In [ ]:
import tensorflow as tf
import numpy as np

np.random.seed(1)
tf.random.set_seed(1234)

In [ ]:
#Zero dimensional tensor
tensor_zero_dim = tf.constant(4)
print(tensor_zero_dim)

#0Dtensor of type string
tensor_zero_dim_1 = tf.constant("hellow world")
print(tensor_zero_dim_1)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(b'hellow world', shape=(), dtype=string)


In [ ]:
#One dimensional tensor
tensor_one_dim = tf.constant([4, 5, 6, 7])
print(tensor_one_dim)

tensor_one_dim_2 = tf.constant(np.arange(4))
print(tensor_one_dim_2)

tensor_one_dim_3 = tf.constant(np.random.randn(4,))
print(tensor_one_dim_3)

tensor_one_dim_4 = tf.constant(np.zeros((4,)))
print(tensor_one_dim_4)

#1Dtensor of type string
tensor_one_dim_5 = tf.constant(["hellow world", "hi"])
print(tensor_one_dim_5)

tf.Tensor([4 5 6 7], shape=(4,), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int64)
tf.Tensor([-0.6871727  -0.84520564 -0.67124613 -0.0126646 ], shape=(4,), dtype=float64)
tf.Tensor([0. 0. 0. 0.], shape=(4,), dtype=float64)
tf.Tensor([b'hellow world' b'hi'], shape=(2,), dtype=string)


In [ ]:
#Two dimensional tensor - 2D
tensor_two_dim = tf.constant([
    [4, 5, 6, 7],
     [1, 2, 3, 4]
    ]) #stack of 1D tensors
print(tensor_two_dim)

tensor_two_dim_2 = tf.constant(np.arange(8).reshape((2, 4)))
print(tensor_two_dim_2)

tensor_two_dim_3 = tf.constant(np.random.randn(2, 4))
print(tensor_two_dim_3)

tensor_two_dim_4 = tf.constant(np.zeros((2, 4)))
print(tensor_two_dim_4)

tf.Tensor(
[[4 5 6 7]
 [1 2 3 4]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int64)
tf.Tensor(
[[ 0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127]], shape=(2, 4), dtype=float64)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(2, 4), dtype=float64)


In [ ]:
#Three dimensional tensor - 3D
tensor_three_dim = tf.constant([
    [[4, 5, 6, 7], [1, 2, 3, 4]],
     [[4, 5, 6, 7], [1, 2, 3, 4]]
    ]) #stack of 2D tensors - how many 2d tensors = 2, each 2D tensor of shape (2 ,4)
    #final shape = (2, 2, 4)
    #our usual method for shape also works, just check the Coursera Conv Introduction notebook
    #vertical line gives horizontal rows, column=channels 2 rows 2 columns for 4 channels
print(tensor_three_dim)

tensor_three_dim_2 = tf.constant(np.arange(16).reshape((2, 2, 4)))
print(tensor_three_dim_2)

tensor_three_dim_3 = tf.constant(np.random.randn(2, 2, 4))
print(tensor_three_dim_3)

tensor_three_dim_4 = tf.constant(np.zeros((2, 2, 4)))
print(tensor_three_dim_4)

tf.Tensor(
[[[4 5 6 7]
  [1 2 3 4]]

 [[4 5 6 7]
  [1 2 3 4]]], shape=(2, 2, 4), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]], shape=(2, 2, 4), dtype=int64)
tf.Tensor(
[[[-0.17242821 -0.87785842  0.04221375  0.58281521]
  [-1.10061918  1.14472371  0.90159072  0.50249434]]

 [[ 0.90085595 -0.68372786 -0.12289023 -0.93576943]
  [-0.26788808  0.53035547 -0.69166075 -0.39675353]]], shape=(2, 2, 4), dtype=float64)
tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 2, 4), dtype=float64)


In [ ]:
#stacking of 3D tensors give the 4D tensor
tensor_four_dim = tf.constant([
    [[[4, 5, 6, 7], [1, 2, 3, 4]],
     [[4, 5, 6, 7], [1, 2, 3, 4]]],

    [[[4, 5, 6, 7], [1, 2, 3, 4]],
     [[4, 5, 6, 7], [1, 2, 3, 4]]]
    ]) #stack of 3D tensors - how many 3d tensors = 2, each 3D tensor of shape (2, 2 ,4) = (2, 2, 2, 4)

print(tensor_four_dim)

tensor_four_dim_2 = tf.constant([
    [[[13, 26, 0., 7],
     [3, 2, 5, 4]],
     [[4, 5, 6, 7],
      [1, 2, 3, 4]]],

    [[[5, 8, 6, 7],
     [2, 75, 65, 4]],
     [[4, 5, 6, 7],
      [1, 2, 3, 4]]],

    [[[75, 7, 5, 77],
     [62, 5, 65, 74]],
     [[4, 85, 86, 7.],
      [1, 2, 3, 49]]]
    ])

print(tensor_four_dim_2)
#also see how having one float value chnages the whole tensor to float dtype

tf.Tensor(
[[[[4 5 6 7]
   [1 2 3 4]]

  [[4 5 6 7]
   [1 2 3 4]]]


 [[[4 5 6 7]
   [1 2 3 4]]

  [[4 5 6 7]
   [1 2 3 4]]]], shape=(2, 2, 2, 4), dtype=int32)
tf.Tensor(
[[[[13. 26.  0.  7.]
   [ 3.  2.  5.  4.]]

  [[ 4.  5.  6.  7.]
   [ 1.  2.  3.  4.]]]


 [[[ 5.  8.  6.  7.]
   [ 2. 75. 65.  4.]]

  [[ 4.  5.  6.  7.]
   [ 1.  2.  3.  4.]]]


 [[[75.  7.  5. 77.]
   [62.  5. 65. 74.]]

  [[ 4. 85. 86.  7.]
   [ 1.  2.  3. 49.]]]], shape=(3, 2, 2, 4), dtype=float32)


In [ ]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3]) #creates a 2D tensor
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
#ndim
tensor_three_dim_4.ndim #3d tensor so gives 3 dimensions

3

## **Casting**

### tf.cast()

  Prefer tf.cast for casting instead of casting with dtype

In [ ]:
#cats a 1D tensor of dtype int to float using dtpe
tensor_i_f = tf.constant([4, 5, 6, 7], dtype=tf.float32)
tensor_i_f

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([4., 5., 6., 7.], dtype=float32)>

In [ ]:
#cast floats to int using dtype throws error
tensor_f_i = tf.constant([4., 5., 6., 7.], dtype=tf.int16)
print(tensor_f_i)

#throws error as it cant cast float to int. In such cases we should use tf.cast to cast floats to int

TypeError: ignored

In [ ]:
#cast floats to int using tf.cast - casts successfully
tensor_f_i = tf.cast(tf.constant([4., 5., 6., 7.]), dtype=tf.int16)
print(tensor_f_i)

tf.Tensor([4 5 6 7], shape=(4,), dtype=int16)


In [ ]:
#cast floats to boolean using tf.cast - casts successfully
tensor_f_b = tf.cast(tf.constant([4., 5., 0., 7.]), dtype=tf.bool)
print(tensor_f_b)

tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [ ]:
#cast int to boolean using tf.cast - casts successfully
tensor_i_b = tf.cast(tf.constant([4, 5, 0, 7]), dtype=tf.bool)
print(tensor_i_b)

tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [ ]:
##cast boolean to int using tf.cast - casts successfully
tensor_b_i = tf.cast(tf.constant([True, False, False, True]), dtype=tf.int64)
print(tensor_b_i)

tf.Tensor([1 0 0 1], shape=(4,), dtype=int64)


## **Initializations**
### tf.convert_to_tensor()
  Convert numpy arrays to tensor

In [ ]:
#tf.convert_to_tensor
myarray = np.array([1, 2, 3])
mytensor = tf.convert_to_tensor(myarray)
print(mytensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


### tf.eye()
  To create identity matrix tensor

In [ ]:
#create 2d identity matrix with 3 rows and same columns, default dtype float32
eye_tensor = tf.eye(num_rows=3)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
#tf.eye with different rows and columns
#create identity matrix with 5 rows and 3 columns but identity only in same rows columns (3x3, remaining 0)
#acts as if the full remainin identity is cut off
eye_tensor = tf.eye(num_rows=5, num_columns=3)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
#tf.eye with different rows and columns
#create identity matrix with 3 rows and 5 columns but identity only in same rows columns (3x3, remaining 0)
#acts as if the full remainin identity is cut off
eye_tensor = tf.eye(num_rows=3, num_columns=5)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]], shape=(3, 5), dtype=float32)


In [ ]:
#tf.eye() with batch_shape
#creates 2d identity matrices as many as specified in batch, batch of 2d matrices
eye_tensor = tf.eye(num_rows=3, num_columns=5, batch_shape=[2,]) #2 3x5 Identity matrices
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]], shape=(2, 3, 5), dtype=float32)


In [ ]:
#tf.eye() with batch_shape
#creates 2d identity matrices as many as specified in batch, batch of 2d matrices
eye_tensor = tf.eye(num_rows=5, num_columns=5, batch_shape=[2,]) #2 5x5 Identity matrices
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [ ]:
#tf.eye() with batch_shape
eye_tensor = tf.eye(num_rows=3, num_columns=5, batch_shape=[2, 4]) #2 4x3x5 Identity matrices => 2 3D matrices
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]]]], shape=(2, 4, 3, 5), dtype=float32)


In [ ]:
#onehotencode the labels of Y using np.eye
num_classes = 6
Y = tf.constant([[1, 2, 4, 0, 5, 3, 2, 3, 0]]) #6 classes - 0 , 1,.. , 5
eye_tensor = tf.eye(num_classes)
print(eye_tensor)
print(tf.reshape(Y, -1).numpy())
Y_onehotencode = np.eye(num_classes)[tf.reshape(Y, -1).numpy()]
print(Y_onehotencode)

tf.Tensor(
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]], shape=(6, 6), dtype=float32)
[1 2 4 0 5 3 2 3 0]
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


In [ ]:
num_classes = 5
# Y is your target labels (assumed to be a 1D TensorFlow tensor)
Y = tf.constant([2, 0, 3, 1, 4])
# Create a one-hot encoding using tf.eye
# one_hot_encoding = tf.eye(num_classes)[Y] #doesnt work in tf
identity_matrix = tf.eye(num_classes)
one_hot_encoding = tf.gather(identity_matrix, Y)
#tf.one_hot(Y, depth=num_classes) #sameoperation
print(one_hot_encoding)

tf.Tensor(
[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


### tf.fill()
  Creates a tensor of given shape filled with a given scalar value

In [ ]:
fill_tensor = tf.fill(dims=[3, 4], value=9)#notice in tf, shape is given as list
print(fill_tensor)

tf.Tensor(
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]], shape=(3, 4), dtype=int32)


In [ ]:
fill_tensor = tf.fill(dims=[1, 3, 4], value=5)#3D tensor
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


###tf.ones()
  
  To create a tensor of given shape with all ones in it. Just like tf.fill()

In [ ]:
tensor_ones = tf.ones([3, 4]) #2D 3 rows 4 columns
print(tensor_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [ ]:
ones_tensor = tf.ones([3, 2, 4]) #3D
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 2, 4), dtype=float32)


###tf.ones_like()

  Creates tensor as same shape as the input tensor, but fill with ones in it

In [ ]:
inp_tensor = tf.constant([[5, 2], [3, 4]])
ones_like_tensor = tf.ones_like(inp_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


### tf.zeros()
   To create a tensor of given shape with all zeros in it

In [ ]:
zeros_tensor = tf.zeros([3, 2, 4]) #3D - 3 rows, 2cols, 4 channels
print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(3, 2, 4), dtype=float32)


### tf.zeros_like()
   To create a tensor as same shape as input tensor, but with all zeros in it

In [ ]:
inp_tensor = tf.constant([[5, 2], [3, 4]])
zeros_like_tensor = tf.zeros_like(inp_tensor)
print(zeros_like_tensor)

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)


### tf.shape()
  Gives the shape of the input tensor. The only difference between inputtensor.shape and tf.shape(inputtensor) is the former one returns only the shape as tuple but the later one returns the tensor with shape as list, number of dimensions(shape attribute) along with dtype

In [ ]:
my_tensor = tf.constant([[[5, 2], [3, 4]]])
print(tf.shape(my_tensor))
print(my_tensor.shape)

tf.Tensor([1 2 2], shape=(3,), dtype=int32)
(1, 2, 2)


### tf.rank()
  Gives the number of dimensions in the tensor

In [ ]:
my_tensor = tf.constant([[[5, 2], [3, 4]]])
print(tf.rank(my_tensor))

tf.Tensor(3, shape=(), dtype=int32)


### tf.size()
  Returns the number of elements in the input tensor

In [ ]:
my_tensor = tf.constant([[[5, 2], [3, 4]]]) #4elements
print(tf.size(my_tensor))

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
my_tensor = tf.constant([
    [[5, 2], [3, 4]], [[1, 5], [7, 8]]
    ]) #8elements
print(tf.size(my_tensor))

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
#outputs the number of elements in the specified dtype
my_tensor = tf.constant([
    [[5, 2], [3, 4]], [[1, 5], [7, 8]]
    ]) #8elements
print(tf.size(my_tensor, out_type=tf.float32))

tf.Tensor(8.0, shape=(), dtype=float32)


### tf.random.normal()
  - Returns a tensor of required shape from random normal distribution

In [ ]:
tf.random.set_seed(1234) #this us also needed for tf backend seed along with normal internal seed argumnt to get reproducible results
random_normal_tensor = tf.random.normal([2, 3], seed=0) #mean, stddev defaults to 0 & 1 resp
print(random_normal_tensor)

#observe how each value is close to zero, and the difference between adjancent vals are close 1

tf.Tensor(
[[-0.30200204  1.9954948  -1.4346613 ]
 [-2.5982814   0.05055132 -0.53368956]], shape=(2, 3), dtype=float32)


In [ ]:
#with specified mean and std
tf.random.set_seed(1234)
random_normal_tensor = tf.random.normal([2, 3], mean=100.0, stddev=1, seed=0)
print(random_normal_tensor)

##observe how each value is close to 100, and the difference between adjancent vals are close 1
#the probability of seeing values close to 100 are more frequent than the ones far from 100

tf.Tensor(
[[ 99.698   101.9955   98.56534]
 [ 97.40172 100.05055  99.46631]], shape=(2, 3), dtype=float32)


### tf.random.uniform()
  Returns a tensor of required shape from random uniform distribution

In [ ]:
tf.random.set_seed(1234)
random_uniform_tensor = tf.random.uniform(shape=[3, 2],
                                         minval=-1., maxval=0., seed=0) #default  minval=0,  maxval=1 in tf
print(random_uniform_tensor)
#see how the values are between -1 and 0

tf.Tensor(
[[-0.8695288  -0.0239054 ]
 [-0.98777974 -0.41970658]
 [-0.13384378 -0.5150304 ]], shape=(3, 2), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
random_uniform_tensor = tf.random.uniform(shape=[4,],
                                         minval=6, maxval=10, seed=0, dtype=tf.int32)
print(random_uniform_tensor)
#see how the values are between 6 and 10

tf.Tensor([6 9 9 8], shape=(4,), dtype=int32)


## **Indexing**

### Indexing with slicing

In [ ]:
indexed_tensor = tf.constant([1, 7, 6, 5, 99, 88])
print(indexed_tensor[0:3])
print(indexed_tensor[1:3]) #starts idx 1, till idx 2
print(indexed_tensor[1:4]) # start idx 1, end idx 3 (3+1 = 4)
print(indexed_tensor[1:3+1]) # start idx 1, end idx 3 (3+1 = 4)
print(indexed_tensor[0:4+1:2]) # start idx 1, end idx 4 , step 2
print(indexed_tensor[2:])
print(indexed_tensor[:4])
print(indexed_tensor[2:-1]) #negative indexing
print(indexed_tensor[2:-2])
print(indexed_tensor[-3:-1]) #short to largest
print(indexed_tensor[-1:-3]) #empty and wrong of indexing
print(indexed_tensor[::-1]) #reverse with negative indexing
print(tf.range(1, 3+1)) #(1, 4) = 1, 2, 3


tf.Tensor([1 7 6], shape=(3,), dtype=int32)
tf.Tensor([7 6], shape=(2,), dtype=int32)
tf.Tensor([7 6 5], shape=(3,), dtype=int32)
tf.Tensor([7 6 5], shape=(3,), dtype=int32)
tf.Tensor([ 1  6 99], shape=(3,), dtype=int32)
tf.Tensor([ 6  5 99 88], shape=(4,), dtype=int32)
tf.Tensor([1 7 6 5], shape=(4,), dtype=int32)
tf.Tensor([ 6  5 99], shape=(3,), dtype=int32)
tf.Tensor([6 5], shape=(2,), dtype=int32)
tf.Tensor([ 5 99], shape=(2,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([88 99  5  6  7  1], shape=(6,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
#Indexing with 2D tensor
indexed_tensor = tf.constant([[1, 2, 0],
                              [3, 5, -1],
                              [1, 5, 6],
                              [2, 3, 8]])

print(indexed_tensor[0:3, 0:2]) #subset - 0:3 - 3 rows and 0:2 - 2 columns

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


In [ ]:
#Indexing with 2D tensor
indexed_tensor = tf.constant([[1, 2, 0],
                              [3, 5, -1],
                              [1, 5, 6],
                              [2, 3, 8]])

print(indexed_tensor[0:3, :]) #subset - 0:3 - 3 rows and : - all columns

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
#Indexing with 2D tensor
indexed_tensor = tf.constant([[1, 2, 0],
                              [3, 5, -1],
                              [1, 5, 6],
                              [2, 3, 8]])

print(indexed_tensor[2, :]) #subset - 2 rows and : - all columns - returns 1D vector

tf.Tensor([1 5 6], shape=(3,), dtype=int32)


In [ ]:
#Indexing with 2D tensor
indexed_tensor = tf.constant([[1, 2, 0],
                              [3, 5, -1],
                              [1, 5, 6],
                              [2, 3, 8]])

print(indexed_tensor[:, 0]) #subset - all rows and 0th idx columns - returns 1D vector

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
#Indexing with three dots ... to get all the values
indexed_tensor = tf.constant([[1, 2, 0],
                              [3, 5, -1],
                              [1, 5, 6],
                              [2, 3, 8]])

print(indexed_tensor[..., 0]) #subset - all rows, 0th column, note only one ellipse possible.

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
#Indexing with single value
indexed_tensor = tf.constant([[1, 2, 0],
                              [3, 5, -1],
                              [1, 5, 6],
                              [2, 3, 8]])

print(indexed_tensor[0]) #0th row, all columns - returns 1D

tf.Tensor([1 2 0], shape=(3,), dtype=int32)


In [ ]:
#Indexing with single value withouspecifying first dimension rows - throws error
indexed_tensor = tf.constant([[1, 2, 0],
                              [3, 5, -1],
                              [1, 5, 6],
                              [2, 3, 8]])

# print(indexed_tensor[, 0]) #trying to access 0th column, without specifying rows. throws error
print(indexed_tensor[:, 0]) #this works - returns 1D(only one ":" there)

tf.Tensor([1 3 1 2], shape=(4,), dtype=int32)


In [ ]:
from numpy.matrixlib.defmatrix import matrix
#Indexing with 3D tensor
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [2, 3, 8]]
    ])

print(indexed_tensor[0, :, :]) #subset - 0th idx position 2D matrix of all rows and all columns
#Remember - 3D can be written as total number of 2D matrices (total 2Dmatrices, num_rows of one 2D matrix, number of cols of one 2D matrix)
#In other notation, they also refer to (num_rows, num_cols, num_channels) in another comprehension - see convnet introductions in DL C4

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
#Indexing with 3D tensor
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [2, 3, 8]]
    ])

print(indexed_tensor[0:2, :, :1]) #subset - 0:2 - 2 rows and : - all columns, channel 1 - returns 3D(three :'s are there)

tf.Tensor(
[[[1]
  [3]]

 [[1]
  [2]]], shape=(2, 2, 1), dtype=int32)


In [ ]:
#Indexing with 3D tensor
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [-2, 3, 8]]
    ])

print(indexed_tensor[1, :, :]) #subset - 1st idx row - 1st idx 2d matrix, all columns, all channels - returns 2D

tf.Tensor(
[[ 1  5  6]
 [-2  3  8]], shape=(2, 3), dtype=int32)


In [ ]:
#Indexing with 3D tensor
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [-2, 3, 8]]
    ])

print(indexed_tensor[1, :2, :1]) #subset - 1st idx 2d matrix, 0,1 rows 2D matrix, 0th column - returns 2D(2 :'s are there so)
#usual indexing way of 1st channel 2nd channel also works i.e 1st row horizontal placing, 0,1 columns, 0th channel(first vertical line)

tf.Tensor(
[[ 1]
 [-2]], shape=(2, 1), dtype=int32)


In [ ]:
#Indexing with three dots ... to get all the values
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [-2, 3, 8]]
    ])

print(indexed_tensor[1, ..., 0]) #subset - 1st idx 2d matrix, all rows, 0th column. note only one ellipse possible.
#- returns 1D as there are 2 straight indexes without : symbol

tf.Tensor([ 1 -2], shape=(2,), dtype=int32)


In [ ]:
#Indexing with three dots ... to get all the values
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [-2, 3, 8]]
    ])

# print(indexed_tensor[1, ..., ...]) #throws error note only one ellipse possible.
print(indexed_tensor[1, ..., :]) #alternative solution

tf.Tensor(
[[ 1  5  6]
 [-2  3  8]], shape=(2, 3), dtype=int32)


In [ ]:
#Indexing with three dots ... to get all the values
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [-2, 3, 8]],
    [[10, 50, 60],
    [29, -3, -8]]
    ])


print(indexed_tensor[:, ..., 2])

tf.Tensor(
[[ 0 -1]
 [ 6  8]
 [60 -8]], shape=(3, 2), dtype=int32)


In [ ]:
#Indexing with three dots ... to get all the values
indexed_tensor = tf.constant([
    [[1, 2, 0],
    [3, 5, -1]],
    [[1, 5, 6],
    [-2, 3, 8]]
    ])

print(indexed_tensor[0:2, ..., 2]) #subset - 0,1 indxed 2d matrices, all rows, last column. see how the last column arranged as rows in the result
#- returns 1D as there are 2 straight indexes without : symbol

tf.Tensor(
[[ 0 -1]
 [ 6  8]], shape=(2, 2), dtype=int32)


## **Math operations**

## tf.math

### tf.math.abs() or tf.abs()
  Gives the absolute value of real numbers. For complex numbers such as a+bj, it gonna give sqrt(a^2 + b^2)

In [ ]:
x = tf.constant([-2.25, 3.25])
x_abs = tf.math.abs(x)
print(x_abs)

tf.Tensor([2.25 3.25], shape=(2,), dtype=float32)


In [ ]:
x_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

### tf.math.add() or tf.add()
  Performs element-wise addition for similar shaped tensor. For dissimilar shaped tensors, it uses the concept of broadcasting and performs the operations if it satisfies the broadcasting rule( 1 or empty shape rule)

  Note: tf.multiply() , tf.subtract(), tf.divide(), tf.math.divide_no_nan() also performs the similar kind of element wise operations

  Note: tf.math.divide_no_nan() performs safe divide which returns 0 if y (denominator) is zero.

In [ ]:
x = tf.constant([1, 3, 2, 5])
y = tf.constant([7, 8, 9, 10])
tf.add(x, y) #element wise addition

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8, 11, 11, 15], dtype=int32)>

In [ ]:
x = tf.constant([1, 3, 2, 5]) #1D
y = tf.constant(1) #0D
tf.add(x, y) #broadcasting element wise addition

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 3, 6], dtype=int32)>

In [ ]:
x = tf.constant([1, 3, 2, 5]) #1D
y = tf.constant([1]) #1D
tf.add(x, y) #broadcasting element wise addition

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 3, 6], dtype=int32)>

In [ ]:
x = tf.constant([1, 3, 2, 5]) #1D - shape - (4,)
y = tf.constant([[1],[2]]) #2D - (2, 1)
tf.add(x, y) #broadcasting element wise addition - result shape 2x4

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 4, 3, 6],
       [3, 5, 4, 7]], dtype=int32)>

### tf.math.maximum() or tf.maximum()
  Returns the element-wise maximum of 2 tensors x and y (i.e. x > y ? x : y).

Note: tf.math.minimum() or tf.minimum() works the same way - element wise minimum


In [ ]:
x = tf.constant([1, 3, 2, 5])
y = tf.constant([7, 8, 9, 10])
tf.math.maximum(x, y) #element wise maximum

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  8,  9, 10], dtype=int32)>

In [ ]:
x = tf.constant([1, 3, 2, 5]) #1D
y = tf.constant([1]) #1D
tf.maximum(x, y) #broadcasting element wise maximum

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 3, 2, 5], dtype=int32)>

In [ ]:
x = tf.constant([1, 3, 2, 5]) #1D
y = tf.constant(1) #0D
tf.maximum(x, y) #broadcasting element wise maximum

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 3, 2, 5], dtype=int32)>

### tf.math.argmax() ot tf.argmax()

  Returns the index having the largest value across specified axes of a tensor.

Note: tf.math.argmax() ot tf.argmax() work same but gives index of minimum value of specfied axis

In [ ]:
A = tf.constant([2, 20, 30, 3, 6])
tf.math.argmax(A)  # A[2] is maximum in tensor A

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.argmax(B, axis=0) #max idxs across 0th axis (axis=0, vertical axis - down arrow direction - all rows, each column)


<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2])>

In [ ]:
B = tf.constant([[2, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
tf.math.argmax(B, 1) #max idxs across 1st axis (axis=1, horizontal axis - -> arrow direction - all columns, each row)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 2, 1])>

In [ ]:
C = tf.constant([0, 0, 0, 0]) ## Returns smallest index in case of ties
tf.math.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

### tf.math.equal(), tf.math.less_equal(), tf.math.greater_equal, tf.math.not_equal
  equal() - Returns the element-wise truth value of 2 tensors(x == y)

  less_equal()- Returns the truth value of (x <= y) element-wise

  greater_equal() - Returns the truth value of (x >= y) element-wise

  not_equal() - Returns the truth value of (x != y) element-wise.

  Also follows broadcasting concept

In [ ]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
x = tf.constant([2, 4])
y = tf.constant([2, 4])
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [ ]:
x = tf.constant([2, 4])
y = tf.constant([2, 3])
tf.math.less_equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
x = tf.constant([2, 4])
y = tf.constant([2])
tf.math.greater_equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [ ]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.not_equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

### tf.math.pow

  Computes the power of one value to another. (element wise)  
  Given a tensor x and a tensor y, this operation computes x**y
 for corresponding elements in x and y.

 x and y can be a tensor od 0 dimensional or even a scalar. It performs elements wise power

In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y) #element wise power

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
x = tf.constant([[2, 2], [3, 3]])
tf.pow(x, 2) #element wise power

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [9, 9]], dtype=int32)>

In [ ]:
x = 3
tf.pow(x, 2) #element wise power

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
y = tf.constant([[2, 2], [3, 3]])
tf.pow(2, y) #element wise power

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [8, 8]], dtype=int32)>

### tf.math.log()
Computes natural logarithm of x element-wise.(log x base e)

In [ ]:
x = tf.constant([0, 0.5, 1, 5, 10])
tf.math.log(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([      -inf, -0.6931472,  0.       ,  1.609438 ,  2.3025851],
      dtype=float32)>

### tf.math.log1p()
  Computes natural logarithm of (1 + x) element-wise.(used to handle numerical instabilities when log is in the denominator eg: binary cross entropy)

In [ ]:
x = tf.constant([0, 0.5, 1, 5, 10])
tf.math.log1p(x) #see how inf in the usual log is replaced with 0(see the prev cell with usual log)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.       , 0.4054651, 0.6931472, 1.7917595, 2.3978953],
      dtype=float32)>

### tf.math.isinf()
  Returns which elements of x are Inf.

In [ ]:
x = tf.constant([5.0, np.inf, 6.8, np.inf])

### tf.math.isnan()

Returns which elements of x are NaN.

In [ ]:
x = tf.constant([5.0, np.nan, 6.8, np.nan, np.inf])
tf.math.is_nan(x)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True, False,  True, False])>

### tf.math.logical_and(), tf.math.logical_or(), tf.math.logical_not(), tf.math.logical_xor()

logical_and() - Returns the truth value of x AND y element-wise. where x and y are tensors of type bool

logical_or() - Returns the truth value of x OR y element-wise.

logical_not() - Returns the truth value of NOT x element-wise.

logical_xor() - Logical XOR function elementwise

all of these supports broadcasting

In [ ]:
a = tf.constant([True])
b = tf.constant([False])
print(tf.math.logical_and(a, b))
print(a & b)

tf.Tensor([False], shape=(1,), dtype=bool)
tf.Tensor([False], shape=(1,), dtype=bool)


In [ ]:
c = tf.constant([True])
x = tf.constant([False, True, True, False])
print(tf.math.logical_and(c, x))
print(c & x)

tf.Tensor([False  True  True False], shape=(4,), dtype=bool)
tf.Tensor([False  True  True False], shape=(4,), dtype=bool)


In [ ]:
y = tf.constant([False, False, True, True])
z = tf.constant([False, True, False, True])
print(tf.math.logical_and(y, z))
print(y & z)

tf.Tensor([False False False  True], shape=(4,), dtype=bool)
tf.Tensor([False False False  True], shape=(4,), dtype=bool)


In [ ]:
tf.logical_and(
    [[True, False]],
 [[True],
  [False]]) #broadcasting

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False]])>

In [ ]:
tf.math.logical_not(tf.constant([True, False]))

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

In [ ]:
a = tf.constant([True])
b = tf.constant([False])
tf.math.logical_xor(a, b)

<tf.Tensor: shape=(1,), dtype=bool, numpy=array([ True])>

In [ ]:
c = tf.constant([True])
x = tf.constant([False, True, True, False])
tf.math.logical_xor(c, x)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False,  True])>

In [ ]:
y = tf.constant([False, False, True, True])
z = tf.constant([False, True, False, True])
tf.math.logical_xor(y, z)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([False,  True,  True, False])>

### tf.math.reduce_sum(), tf.math.reduce_max(), tf.math.reduce_min(), tf.math.reduce_mean(), tf.math.reduce_std(), tf.math.reduce_variance(), tf.math.reduce_prod(), tf.reduce_euclidean_norm()

reduce_sum() - Computes the sum of elements across dimensions of a tensor.

reduce_min() - Computes the min of elements across dimensions of a tensor.

reduce_max() - Computes the max of elements across dimensions of a tensor.

reduce_mean() - Computes the mean of elements across dimensions of a tensor.

reduce_std() - Computes the std of elements across dimensions of a tensor.

reduce_variance() - Computes the variance of elements across dimensions of a tensor.

reduce_prod() - Computes tf.math.multiply of elements across dimensions of a tensor.

reduce_euclidean_norm() - Computes the Euclidean norm of elements across dimensions of a tensor.

If axis is None, all dimensions are reduced(reduce from axis=0 and then axis=1 for 2D axis), and a tensor with a single element is returned.

Note: Difference between add and reduce_sum is: add is element wise sum of 2 or more tensors, reduce sum performs sum on the tensor itself based on axis. Reduces the tensor to a value based on operation and axis. Same applies to others operations as well

In [ ]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])
print(tf.reduce_sum(x)) #when no axis specified, the matrix is reduced to overall sum
print(tf.reduce_sum(x).numpy())

tf.Tensor(6, shape=(), dtype=int32)
6


In [ ]:
x = tf.constant([[1, 2, 9], [17, 109, 1777]])
print(tf.reduce_max(x)) #when no axis specified, the matrix is reduced to max of the overall matrix

tf.Tensor(1777, shape=(), dtype=int32)


In [ ]:
x = tf.constant([[1, 2, 9], [17, 109, 1777]])
print(tf.math.reduce_min(x)) #when no axis specified, the matrix is reduced to min of the overall matrix

tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
x = tf.constant([[1, 2, 9], [17, 109, 1777]])
print(tf.math.reduce_mean(x)) #when no axis specified, the matrix is reduced to mean of the overall matrix

tf.Tensor(319, shape=(), dtype=int32)


In [ ]:
x = tf.constant([[1, 2, 9], [17, 109, 1777]], dtype=tf.float32)
print(tf.math.reduce_std(x)) #when no axis specified, the matrix is reduced to std of the overall matrix

tf.Tensor(653.04175, shape=(), dtype=float32)


In [ ]:
#reduce along the first dimension
x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x, 0) #axis 0

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>

In [ ]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x, 0).numpy() #axis 0

array([2, 2, 2], dtype=int32)

In [ ]:
#reduce along the first dimension
x = tf.constant([[1, 1, 1], [1, 1, 1]])
print(x.shape)
tf.reduce_sum(x, 1) #axis 0

(2, 3)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [ ]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])
print(tf.reduce_sum(x, axis=0)) #without keep_dims
print(tf.reduce_sum(x, axis=0, keepdims=True)) #axis 0 with keep_dims to retain the original dimensions (2 dimensions)

tf.Tensor([2 2 2], shape=(3,), dtype=int32)
tf.Tensor([[2 2 2]], shape=(1, 3), dtype=int32)


In [ ]:
# reduce along both dimensions - axis 0 and 1
# the result is 1 + 1 + 1 + 1 + 1 + 1 = 6
# or, equivalently, reduce along rows, then reduce the resultant array
# [1, 1, 1] + [1, 1, 1] = [2, 2, 2] #axis = 0
# 2 + 2 + 2 = 6 #axis 1
x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x, [0, 1]).numpy()

6

In [ ]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_prod(x) #no axis, reduces from both axis

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [ ]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_prod(x, 0) #axis = 0

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 8.], dtype=float32)>

In [ ]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_prod(x, 1) #axis = 1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2., 12.], dtype=float32)>

In [ ]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_prod(x, 1, keepdims=1) #axis = 1, keep dims, see it was 2, 1

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 2.],
       [12.]], dtype=float32)>

In [ ]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_prod(x, 0, keepdims=1) #axis=0, keep dims, see it was 1, 2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[3., 8.]], dtype=float32)>

In [ ]:
x = tf.constant([[1, 2, 3], [1, 1, 1]]) # x.dtype is tf.int32
tf.math.reduce_euclidean_norm(x)  # returns 4 as dtype is tf.int32
#euclidean norm = sqrt(elem1^2 + elem2^2 + ..)
#axis=0 [sqrt(2), sqrt(5), sqrt(10)]
#axis=1 [sqrt(17)] = 4.12

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
y = tf.constant([[1, 2, 3], [1, 1, 1]], dtype = tf.float32)
print(tf.math.reduce_euclidean_norm(y))  # returns 4.1231055 which is sqrt(17)
print(tf.math.reduce_euclidean_norm(y, 0))  # [sqrt(1^2+1^2), sqrt(2^2+1^2), sqrt(3^2+1^2)] = sqrt(2), sqrt(5), sqrt(10)
print(tf.math.reduce_euclidean_norm(y, 1))  # [sqrt(14), sqrt(3)]
print(tf.math.reduce_euclidean_norm(y, 1, keepdims=True))  # [[sqrt(14)], [sqrt(3)]]
print(tf.math.reduce_euclidean_norm(y, [0, 1]))  # sqrt(17)

tf.Tensor(4.1231055, shape=(), dtype=float32)
tf.Tensor([1.4142135 2.236068  3.1622777], shape=(3,), dtype=float32)
tf.Tensor([3.7416575 1.7320508], shape=(2,), dtype=float32)
tf.Tensor(
[[3.7416575]
 [1.7320508]], shape=(2, 1), dtype=float32)
tf.Tensor(4.1231055, shape=(), dtype=float32)


### tf.math.top_k
  Finds values and indices of the k largest entries for the last dimension.(if 2d, 1st dim is axis=0, last dim is axis=1).

  If k=1, it gives 1 top value(1 max value) as output. Note it also gives indices of that top k values

In [ ]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=3)
print(result)
print(result.values)
print(result.values.numpy())
print(result.indices.numpy())

TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99, 98, 96], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9], dtype=int32)>)
tf.Tensor([99 98 96], shape=(3,), dtype=int32)
[99 98 96]
[5 2 9]


In [ ]:
result = tf.math.top_k([[1, 2, 98, 1], [1, 99, 3, 1], [3, 96, 4, 1]],
                        k=1)
print(result) #topk across last dimension i.e axis=1
#k=1 so one top values in axis=1

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[98],
       [99],
       [96]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [1],
       [1]], dtype=int32)>)


In [ ]:
result = tf.math.top_k([[1, 2, 98, 1], [1, 99, 3, 1], [3, 96, 4, 1]],
                        k=2)
print(result) #topk across last dimension i.e axis=1, k=2 so 2 top k values

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[98,  2],
       [99,  3],
       [96,  4]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [1, 2],
       [1, 2]], dtype=int32)>)


In [ ]:
#For matrices (resp. higher rank input), computes the top k entries in each row (resp. vector along the last dimension).
tf.random.set_seed(1234)
input = tf.random.normal(shape=(2, 3, 2, 3), seed=0)
print(input)
k = 2
values, indices  = tf.math.top_k(input, k=k)
print(values)
values.shape.as_list()


tf.Tensor(
[[[[-0.30200204  1.9954948  -1.4346613 ]
   [-2.5982814   0.05055132 -0.53368956]]

  [[-0.0854836   1.5320591   0.35252017]
   [ 0.98868173  1.8347502   0.25095692]]

  [[ 0.64548075 -1.407402   -0.18503316]
   [ 0.98474926  0.20494133  1.5215894 ]]]


 [[[ 1.2456934   0.4704631  -0.21835677]
   [-1.4909089   0.11602011  0.45168912]]

  [[ 2.0852451   0.53211415  0.6841117 ]
   [-0.30278924  1.060474   -1.8116522 ]]

  [[-0.5746191  -0.5106603  -0.32946828]
   [ 0.6081559  -0.08115963  0.17485009]]]], shape=(2, 3, 2, 3), dtype=float32)
tf.Tensor(
[[[[ 1.9954948  -0.30200204]
   [ 0.05055132 -0.53368956]]

  [[ 1.5320591   0.35252017]
   [ 1.8347502   0.98868173]]

  [[ 0.64548075 -0.18503316]
   [ 1.5215894   0.98474926]]]


 [[[ 1.2456934   0.4704631 ]
   [ 0.45168912  0.11602011]]

  [[ 2.0852451   0.6841117 ]
   [ 1.060474   -0.30278924]]

  [[-0.32946828 -0.5106603 ]
   [ 0.6081559   0.17485009]]]], shape=(2, 3, 2, 2), dtype=float32)


[2, 3, 2, 2]

## **Linear Algebra Operations**

## tf.linalg

### tf.linalg.matmul()
  Multiplies matrix a by matrix b, producing a * b.
  
  This must follows the rule number  of columns in matrix A = num of rows in matrix B

In [ ]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([0, -2, -4, 6, 5, 4], shape=[2, 3])
print(a)
print(b)
#print(tf.linalg.matmul(a, b)) #throws error as ncols_a != nrows_b
print(tf.linalg.matmul(a, tf.transpose(b))) #gives a 2x2 resultant matrix
print(tf.linalg.matmul(a, b, transpose_b=True)) #this also transposes b and performes matmul
# print(tf.linalg.matmul(x1, x2, transpose_b=True)) #generally x1 and x2 are 2 tensors, where a is x1 and b is x2

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 0 -2 -4]
 [ 6  5  4]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-16  28]
 [-34  73]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-16  28]
 [-34  73]], shape=(2, 2), dtype=int32)


In [ ]:
#using @ operator for matrix multiplication
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([0, -2, -4, 6, 5, 4], shape=[2, 3])
print(a)
print(b)
a @ tf.transpose(b) #gives a 2x2 resultant matrix

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 0 -2 -4]
 [ 6  5  4]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-16,  28],
       [-34,  73]], dtype=int32)>

<img src = "https://drive.google.com/uc?id=1m7tQ74RGWwqK2IGQs-drgHdDBi2aGRCq"/>


In [ ]:
#matmul for 3D matrix
# the input batches i.e inner 2d matrices shapes should follow matmul rule ncols_a = nrows_b
x1 = tf.constant([
    [[1, 2, 98, 1], [1, 99, 3, 1]],
     [[3, 96, 4, 1], [10, 9, 8, 10]],
    [[3, 96, 4, 1], [10, 9, 8, 10]]
    ])

x2 = tf.constant([
    [[7, 8, 9, 0], [-1, 9, 5, 4]],
    [[4, 6, 2, 1], [-10, 2, 1, -1]],
    [[4, 6, 2, 1], [-10, 2, 1, -1]],
    ])
print(x1.shape) # 3, 2, 4
print(x2.shape) # 3, 2, 4

#inner 2D matrices have x1 - (2, 4), x2 - (2, 4) => 4 !=2,
#so we need to match the matrix inner batches shapes(2D matrices shapes) to follow the matmul rule
# print(x1 @ x2) # throws error
print(tf.transpose(x1).shape) #4, 2, 3
print(tf.transpose(x2).shape) #4, 2, 3

# print(x1 @ tf.transpose(x2)) # (3, 2, 4 ) (4, 2, 3) => (2, 4), (2, 3), doesnt match the rule
# print(tf.transpose(x1) @ x2) #  (4, 2, 3) (3, 2, 4 ) => (2, 3), (2, 4), doesnt match the rule
# print(tf.transpose(x1) @ tf.transpose(x2)) #(4, 2, 3) (4, 2, 3) => (2, 3) , (2, 3) , doesnt match the rule

#lets change x1 so that the inner matrice rule matches
x1 = tf.constant([
    [[1, 2], [98, 1], [1, 99], [3, 1]],
    [[3, 96], [4, 1], [10, 9], [8, 10]],
    [[4, 6], [2, 1], [-10, 2], [1, -1]]
    ]) # (3, 4, 2)

x2 = tf.constant([
    [[7, 8, 9, 0], [-1, 9, 5, 4]],
    [[4, 6, 2, 1], [-10, 2, 1, -1]],
    [[4, 6, 2, 1], [-10, 2, 1, -1]],
    ]) #(3, 2, 4)

print(x1 @ x2) # output shape (3, 4, 4)
#(3, 4, 2) (3, 2, 4) => (4, 2) (2, 4) = (4, 4) #matches the rule, also note the no. of batches (no. of 2D should match) 3 = 3
#each inner 2d matrix from x1 multiplies with each inner 2d matrux if x2, batch multiplications where each batch is each 2D matrix in both matrices

(3, 2, 4)
(3, 2, 4)
(4, 2, 3)
(4, 2, 3)
tf.Tensor(
[[[   5   26   19    8]
  [ 685  793  887    4]
  [ -92  899  504  396]
  [  20   33   32    4]]

 [[-948  210  102  -93]
  [   6   26    9    3]
  [ -50   78   29    1]
  [ -68   68   26   -2]]

 [[ -44   36   14   -2]
  [  -2   14    5    1]
  [ -60  -56  -18  -12]
  [  14    4    1    2]]], shape=(3, 4, 4), dtype=int32)


In [ ]:
#tf.linalg.matmul with a_sparse argument
#Instructs tf that the matrix is sparse so that it does computations desgined for sparse tensors rather than normal tensors
#sparse tensor is a tensor where mostly it has zeros
x1 = tf.constant([
    [[0, 2], [0, 1], [0, 0], [0, 1]],
    [[0, 0], [0, 1], [0, 0], [0, 1]],
    [[0, 0], [0, 1], [-10, 0], [0, 0]]
    ]) # (3, 4, 2)

x2 = tf.constant([
    [[0, 2, 0, 1], [0, 0, 0, 1]],
    [[0, 0, 0, 1], [0, 0, 0, 1]],
    [[0, 0, 0, 1], [-10, 0, 0, 0]]
    ]) #(3, 2, 4)

# print(tf.sparse.sparse_dense_matmul(x1, x2)) #need to conver the tensor to sparse tensor first

### tf.linalg.band_part

  Copy a tensor, setting everything outside a given central band(limit) in each innermost matrix to zero.

  Given,

  The band part is computed as follows: Assume input has k dimensions [I, J, K, ..., M, N], then the output is a tensor with the same shape where
  band[i, j, k, ..., m, n] = in_band(m, n) * input[i, j, k, ..., m, n].

The indicator function:

in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper).

Here m, n are positions of each value in the tensor. index of mth row, index of nth column, literally take the index values of the position

The working of band_part is, for each position m,n(mth row, nth col), if (num_lower<0) or (m-n)<=num_lower)  and (num_upper<0 or (n-m)<=num_upper), then

in_band(m, n) result is multiplied with input tensor. If in_band(m, n) is true, the input remains same, else if in_band(m, n) is False then, when multiplied with input tensor, the resultant value will be zero (False = 0 , 0*inpvalue = 0)

In [ ]:
input = [[ 0,  1,  2, 3],
        [-1,  0,  1, 2],
        [-2, -1,  0, 1],
        [-3, -2, -1, 0]],

print(tf.linalg.band_part(input, num_lower=1, num_upper=-1))
#return same shape but, the values outside the band i.e limit 1 to -1, is changes to zero

print(tf.linalg.band_part(input, 2, 1))

tf.Tensor(
[[[ 0  1  2  3]
  [-1  0  1  2]
  [ 0 -1  0  1]
  [ 0  0 -1  0]]], shape=(1, 4, 4), dtype=int32)
tf.Tensor(
[[[ 0  1  0  0]
  [-1  0  1  0]
  [-2 -1  0  1]
  [ 0 -2 -1  0]]], shape=(1, 4, 4), dtype=int32)


In [ ]:
#Special cases
input = [[ 1,  1,  2, 3],
        [-1,  1,  1, 2],
        [-2, -1,  1, 1],
        [-3, -2, -1, 1]]
print(tf.linalg.band_part(input, 0, -1)) #Upper triangular part.
print(tf.linalg.band_part(input, -1, 0)) # Lower triangular part.
print(tf.linalg.band_part(input, 0, 0)) # Diagonal.

tf.Tensor(
[[[1 1 2 3]
  [0 1 1 2]
  [0 0 1 1]
  [0 0 0 1]]], shape=(1, 4, 4), dtype=int32)
tf.Tensor(
[[[ 1  0  0  0]
  [-1  1  0  0]
  [-2 -1  1  0]
  [-3 -2 -1  1]]], shape=(1, 4, 4), dtype=int32)
tf.Tensor(
[[[1 0 0 0]
  [0 1 0 0]
  [0 0 1 0]
  [0 0 0 1]]], shape=(1, 4, 4), dtype=int32)


### tf.linalg.inv

  Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes)

  The matrices should be square matrices. The input is a tensor of shape [..., M, M] whose inner-most 2 dimensions form square matrices. The output is a tensor of the same shape as the input containing the inverse for all input submatrices [..., :, :].

In [ ]:
input = tf.constant([[[ 1,  1,  2],
        [-1,  1,  1],
        [2,   3,  4]],
        [[-2, -1,  1],
        [-3, -2, -1],
        [-2, -3, -4]]
    ], dtype=tf.float32) #2, 3, 3 #3, 3 matches => inner square matrix

input_inv = tf.linalg.inv(input)
print(input_inv) #same as input shape 2, 3, 3

print(input @ input_inv) # gives Identity Matrix , A A^-1 = I

tf.Tensor(
[[[-0.33333325 -0.6666667   0.33333337]
  [-2.          0.          1.        ]
  [ 1.6666666   0.33333334 -0.6666667 ]]

 [[ 1.         -1.4000001   0.6000001 ]
  [-2.          2.0000002  -1.0000001 ]
  [ 1.         -0.8000001   0.20000003]]], shape=(2, 3, 3), dtype=float32)
tf.Tensor(
[[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
  [-1.1920929e-07  1.0000000e+00 -5.9604645e-08]
  [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]

 [[ 1.0000000e+00 -1.1920929e-07 -1.4901161e-08]
  [ 0.0000000e+00  9.9999988e-01  1.4901161e-08]
  [ 0.0000000e+00 -4.7683716e-07  1.0000002e+00]]], shape=(2, 3, 3), dtype=float32)


### tf.linalg.svd()
  Computes the singular value decompositions of one or more matrices.

  Singular value decomposition (SVD) is a method of representing a matrix as a series of linear approximations that expose the underlying meaning-structure of the matrix. The goal of SVD is to find the optimal set of factors that best predict the outcome.

  The singular value decomposition of a matrix A is the factorization of A into the product of three matrices A = $U \Sigma V^H$ where the columns of U and V are orthonormal and the matrix $\Sigma$ is diagonal with positive real entries.

  Computes the SVD of each inner matrix in tensor such that tensor[..., :, :] = u[..., :, :] * diag(s[..., :, :]) * transpose(conj(v[..., :, :]))

  It outputs 3 matrices S, U, V
  - s is a tensor of singular values.
  - u is a tensor of left singular vectors.
  - v is a tensor of right singular vectors.

  input tensor - tensor	Tensor of shape [..., M, N]. Let P be the minimum of M and N

  s - 	Singular values. Shape is [..., P]. The values are sorted in reverse order of magnitude, so s[..., 0] is the largest value, s[..., 1] is the second largest, etc.
  
  u	- Left singular vectors. If full_matrices is False (default) then shape is [..., M, P]; if full_matrices is True then shape is [..., M, M]. Not returned if compute_uv is False.

  v	- Right singular vectors. If full_matrices is False (default) then shape is [..., N, P]. If full_matrices is True then shape is [..., N, N]. Not returned if compute_uv is False.

  Mostly equivalent to numpy.linalg.svd, except that
  
 -  The order of output arguments here is s, u, v when compute_uv is True, as opposed to u, s, v for numpy.linalg.svd.

- full_matrices is False by default as opposed to True for numpy.linalg.svd.
- tf.linalg.svd uses the standard definition of the SVD A=$U \Sigma V^H$, such that the left singular vectors of A are the columns of U, while the right singular vectors of A are the columns of V.
- On the other hand, numpy.linalg.svd returns the adjoint $V^H$ as the third output argument.

In [ ]:
# a is a input tensor.
# s is a tensor of singular values.
# u is a tensor of left singular vectors.
# v is a tensor of right singular vectors.

a = tf.constant([[[ 1,  1,  2, 6],
        [-1,  1,  1, 7],
        [2,   3,  4, 6]],
        [[-2, -1,  1, 8],
        [-3, -2, -1, 5],
        [-2, -3, -4, 3]]
    ], dtype=tf.float32) #(2, 3, 4)
s, u, v = tf.linalg.svd(a)
print(s) #(2, 3)
print(u) #(2, 3, 3)
print(v) #(2, 4, 3)

tf.Tensor(
[[12.131628    3.3344274   0.83977455]
 [11.0912485   4.7962112   0.99026895]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[-0.5306773   0.06633792  0.84497404]
  [-0.55966     0.7212651  -0.40811452]
  [-0.6365236  -0.6894752  -0.3456323 ]]

 [[ 0.7116787  -0.57218575  0.40757483]
  [ 0.556381    0.10487431 -0.82428265]
  [ 0.42889872  0.81339103  0.39299005]]], shape=(2, 3, 3), dtype=float32)
tf.Tensor(
[[[-0.10254733 -0.6099628   0.6690183 ]
  [-0.24728003 -0.38412052 -0.71452165]
  [-0.34349144 -0.57100046 -0.1199076 ]
  [-0.90019464  0.3928806   0.1658176 ]]

 [[-0.3561636  -0.16617993  0.88028467]
  [-0.28050375 -0.43320367  0.06262962]
  [-0.14067818 -0.81952703 -0.34344497]
  [ 0.8801562  -0.33629498  0.3212815 ]]], shape=(2, 4, 3), dtype=float32)


In [ ]:
a = tf.constant([[[ 1,  1,  2],
        [-1,  1,  1],
        [2,   3,  4]],
        [[-2, -1,  1],
        [-3, -2, -1],
        [-2, -3, -4]]
    ], dtype=tf.float32)
s = tf.linalg.svd(a, compute_uv=False) #we can also get just the singular values tensor
print(s)

tf.Tensor(
[[5.978355   1.4634548  0.34289432]
 [6.35129    2.9306948  0.26861963]], shape=(2, 3), dtype=float32)


In [ ]:
#Numpy and tf to svd of matrix A
import tensorflow as tf
import numpy as np

a = tf.constant([[ 1,  1,  2],
        [-1,  1,  1],
        [2,   3,  4]], dtype=tf.float32)

s, u, v = tf.linalg.svd(a)
tf_a_approx = tf.matmul(u, tf.matmul(tf.linalg.diag(s), v, adjoint_b=True))
u, s, v_adj = np.linalg.svd(a, full_matrices=False)
np_a_approx = np.dot(u, np.dot(np.diag(s), v_adj))
print(tf_a_approx)
print(np_a_approx)
print(np.allclose(tf_a_approx, np_a_approx))
# tf_a_approx and np_a_approx should be numerically close.

tf.Tensor(
[[ 0.99999994  1.0000001   2.0000005 ]
 [-0.9999997   0.99999976  1.0000001 ]
 [ 2.0000002   3.0000005   4.000001  ]], shape=(3, 3), dtype=float32)
[[ 0.99999994  0.99999994  1.9999999 ]
 [-1.          1.          0.99999994]
 [ 2.          2.9999998   3.9999993 ]]
True


## **Matrix Opertions using tf**

### tf.einsum()
  Tensor contraction over specified indices and outer product.

  einsum is used to perform any kind matrices multiplication by specifying the input indices and output indices irrespective of the multiplication rules.


  Einsum can do matrix multiplication similar to matmul, and it performs matmul for the matrices of any number of dimensions. The only difference is the way we give the input

  We know,the matmul of A and B is possible only if A and B has shapes (i, j) (j, k) and the output is (i,k)

  In np or tf, we give tf.matmul(A, B) or np.matmul(A, B)

  For einsum, we give the condition of matrices matching rule and the resulttant output using placeholder variables.

  np.einsum("ij, jk -> ik", A, B) -> This performs matmul of A, B when the specifed condition is true
  
  Here i represents rows, j represents cols of A, Likewise j-rows, k-cols for B

  Likethis, einsum can not only does matmul. It can do other operations like element wise multiplication. We just have to change the rule. For element wise, we know A and B should have same shapes like for eg (3, 4) (3, 4) or more generally (i, j) (i, j) and the output will be (i, j) again(braodcasting rule)
  
  So, to do element wise multiplication in einsum, we can go write as below
  tf.einsum("ij, ij -> ij", A, B).

  This perform similar operation of A * B or equivalently np.multiply(A, B) or tf.multiply(A, B)

  - Why einsum when we have matmul, multiply directly?
    - In some application einsum is good than numpy matmul operations. for example


In [ ]:
#einsum for matmul
a = tf.constant([[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [2,   3,  4, 1]], dtype=tf.float32)

b = tf.constant([
        [ -1,  11, 32, 6, 4],
        [1,  2,  3, 4, 5],
        [6,   7,  8, 9, 10],
        [ -1,  11,  32, 6, 4]], dtype=tf.float32)

print(a.shape)
print(b.shape)

print("\n"+str(np.matmul(a, b)))

print("\n"+str(np.einsum("ij, jk -> ik", a, b)))

print("\n"+str(tf.einsum("ij, jk -> ik", a, b)))

(3, 4)
(4, 5)

[[  4. 115. 307.  76.  61.]
 [  2.  64. 171.  43.  35.]
 [ 24.  67. 137.  66.  67.]]

[[  4. 115. 307.  76.  61.]
 [  2.  64. 171.  43.  35.]
 [ 24.  67. 137.  66.  67.]]

tf.Tensor(
[[  4. 115. 307.  76.  61.]
 [  2.  64. 171.  43.  35.]
 [ 24.  67. 137.  66.  67.]], shape=(3, 5), dtype=float32)


In [ ]:
#einsum for elementwise multiplication
a = tf.constant([[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [2,   3,  4, 1]], dtype=tf.float32)

b = tf.constant([
        [ -1,  11, 32, 6],
        [1,  2,  3, 4],
        [6,   7,  8, 9]], dtype=tf.float32)

print(a.shape)
print(b.shape)

print("\n"+str(a * b))

print("\n"+str(np.einsum("ij, ij -> ij", a, b)))

print("\n"+str(tf.einsum("ij, ij -> ij", a, b)))

(3, 4)
(3, 4)

tf.Tensor(
[[-1. 11. 64. 48.]
 [-1.  2.  3. 24.]
 [12. 21. 32.  9.]], shape=(3, 4), dtype=float32)

[[-1. 11. 64. 48.]
 [-1.  2.  3. 24.]
 [12. 21. 32.  9.]]

tf.Tensor(
[[-1. 11. 64. 48.]
 [-1.  2.  3. 24.]
 [12. 21. 32.  9.]], shape=(3, 4), dtype=float32)


In [ ]:
#einsum for matrix transpose
a = tf.constant([[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [2,   3,  4, 1]], dtype=tf.float32)

print(a.shape)
print("\n"+str(tf.transpose(a)))

print("\n"+str(tf.einsum("ij -> ji", a)))

(3, 4)

tf.Tensor(
[[ 1. -1.  2.]
 [ 1.  1.  3.]
 [ 2.  1.  4.]
 [ 8.  6.  1.]], shape=(4, 3), dtype=float32)

tf.Tensor(
[[ 1. -1.  2.]
 [ 1.  1.  3.]
 [ 2.  1.  4.]
 [ 8.  6.  1.]], shape=(4, 3), dtype=float32)


In [ ]:
#einsum for matrix multiplication that doesnt follow the matmul rule
a = tf.constant([[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [2,   3,  4, 1]], dtype=tf.float32)

b = tf.constant([
        [ -1,  11, 32, 6],
        [1,  2,  3, 4],], dtype=tf.float32)

print(a.shape)
print(b.shape)

# print("\n"+str(np.matmul(a, b))) #throws error as rule is not followed

print("\n"+str(np.einsum("ij, kj -> ij", a, b))) #but einsum does the multiplication, see the indices, we can configure how we want the output too

print("\n"+str(tf.einsum("ij, kj -> ij", a, b))) #see how the output is changing as per the given indices

(3, 4)
(2, 4)

[[  0.  13.  70.  80.]
 [  0.  13.  35.  60.]
 [  0.  39. 140.  10.]]

tf.Tensor(
[[  0.  13.  70.  80.]
 [ -0.  13.  35.  60.]
 [  0.  39. 140.  10.]], shape=(3, 4), dtype=float32)


In [ ]:
#einsum with 3D matrices
a = tf.constant([
        [[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [6,  9,  1, 6]],
        [[2,   3,  4, 1],
         [-1,  1,  1, 6],
         [1,   2,  3, 4]]
      ], dtype=tf.float32) #2, 3, 4

b = tf.constant([
        [[ 1,  1,  2],
        [-5,  3,  3],
        [6,  9,  1],
        [6,  1,  2]],
        [[2,   3,  4],
         [-1,  1,  1],
         [3,   2,  5],
         [1,   8,  9]]
      ], dtype=tf.float32) #2, 4, 3

print(a.shape) #b, i, j
print(b.shape) #b, j, k

print("\n"+str(np.matmul(a, b))) #2, 3, 3

print("\n"+str(np.einsum("ijk, ikl -> ijl", a, b)))


(2, 3, 4)
(2, 4, 3)

[[[56. 30. 23.]
  [36. 17. 14.]
  [ 3. 48. 52.]]

 [[14. 25. 40.]
  [ 6. 48. 56.]
  [13. 43. 57.]]]

[[[56. 30. 23.]
  [36. 17. 14.]
  [ 3. 48. 52.]]

 [[14. 25. 40.]
  [ 6. 48. 56.]
  [13. 43. 57.]]]


In [ ]:
#sum operation using einsum
a = tf.constant([
        [[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [6,  9,  1, 6]],
        [[2,   3,  4, 1],
         [-1,  1,  1, 6],
         [1,   2,  3, 4]]
      ], dtype=tf.float32) #2, 3, 4

print(a.shape) #b, i, j

print("\n"+str(np.sum(a))) #scalar value

print("\n"+str(np.einsum("bij -> ", a))) #when we dont specify the output indices, then einsum performs sum operation


(2, 3, 4)

68.0

68.0


In [ ]:
#sum operation across axis using einsum
a = tf.constant([[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [6,  9,  1, 6]], dtype=tf.float32) #3, 4

print(a.shape) #i, j

print("\n"+str(np.sum(a, axis=0))) #4, (vertical)

print("\n"+str(np.einsum("ij -> j", a))) #performs sum across all columns and j corresponds to columns

print("\n"+str(np.sum(a, axis=1))) #3, (horizontal)

print("\n"+str(np.einsum("ij -> i", a))) #performs sum across all rows and i corresponds to rows

(3, 4)

[ 6. 11.  4. 20.]

[ 6. 11.  4. 20.]

[12.  7. 22.]

[12.  7. 22.]


In [ ]:
#einsum application - in paper "Attention is all you need"
#There is a formula in this paper Q K.T

#using einsum we can easily implement that
#Q shape (batch_size, s_q, modelsize)
#K shape (batch_size, s_k, modelsize)

Q = np.random.randn(32, 64, 512) #b q m
K = np.random.randn(32, 128, 512) #b k m

#performing that Q K.T easily using einsum
result = np.einsum("bqm, bkm -> bqk", Q, K) #we need q m and m k to perform this multiplication to get bqk right, so watch the condition inside eisum
print(result.shape) #see we can acheive that easily
# print(result)

(32, 64, 128)


In [ ]:
#another einsum application - in paper "Reformer: The efficient transformer"
#In this, they divide the data into buckets A (b c z) - (b c i k) i.e(1, 4, 8) (1, 4, 4, 2)
#Similarly for B (1, 4, 4) to (1, 4, 4, 1) (b c y) - (b c i k)

#the multiplication is B.T A
#using einsum we can easily implement the multiplication between Btranspose and A


A = np.random.randn(2, 4, 4, 2) #b c i j
B = np.random.randn(2, 4, 4, 1) #b c i k

#performing that A.T B easily using einsum
result = np.einsum("bcik, bcij -> bckj", B, A)
print(result.shape)

#usual matmul, we have to transpose first and then perform operation
result = np.matmul(np.transpose(B, (0, 1, 3, 2)), A) #transposing the indexes 2, 3 to 3, 2 for B and this implemention is not cleaner and readable compared to einsum
print(result.shape)

(2, 4, 1, 2)
(2, 4, 1, 2)


## **Common Tensorflow functions**

### tf.expand_dims()
   Adds an extra axis to the input tensor at the specified axis position

In [ ]:
a = tf.constant([[[ 1,  1,  2, 8],
        [-1,  1,  1, 6],
        [-1,  1,  1, 6]],
        [[6,  9,  1, 6],
        [8,  3,  -1, 3],
         [-1,  1,  1, 6]]], dtype=tf.float32)

print(a.shape)

print(tf.expand_dims(a, axis=0).shape) #expand the dimensions at 0th axis - first axis
print(tf.expand_dims(a, axis=1).shape) ##expand the dimensions at 1st axis - second axis
print(tf.expand_dims(a, axis=2).shape) ##expand the dimensions at 2nd axis - third axis
print(tf.expand_dims(a, axis=3).shape) ##expand the dimensions at 3rd axis - fourth axis

(2, 3, 4)
(1, 2, 3, 4)
(2, 1, 3, 4)
(2, 3, 1, 4)
(2, 3, 4, 1)


In [ ]:
#expand_dims for 1D tensor to 2D tensor
a = tf.constant([1, 2, 3, 4]) #1D tensor
print(a.shape)

res = tf.expand_dims(a, axis=0) #expand the dimensions at oth axis - first axis
print(res.shape)
print(res)

(4,)
(1, 4)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


In [ ]:
#expand_dims for 2D tensor to 3D tensor
a = tf.constant([[1, 2, 3, 4]]) #2D tensor
print(a.shape)

res = tf.expand_dims(a, axis=0) #expand the dimensions at oth axis - first axis
print(res.shape)
print(res)

(1, 4)
(1, 1, 4)
tf.Tensor([[[1 2 3 4]]], shape=(1, 1, 4), dtype=int32)


### tf.squeeze()
  Opposite of expand_dims().

  expand_dims() add one axis at the specified axis location

  squeeze() removes dimensions of size 1 from the shape of a tensor.

In [ ]:
#np.squeeze()

#lets expand the dims to understand the effect of squeeze
a = tf.constant([[1, 2, 3, 4]]) #2D tensor
print(a.shape)

expanded_a = tf.expand_dims(a, axis=0) #expand the dimensions at 0th axis - first axis
print(expanded_a.shape)

squeezed_a = tf.squeeze(expanded_a) #removes all dimensions with 1, when no axis is specified - this is inplace operation, hence copying a
print(squeezed_a)

squeezed_a = tf.squeeze(expanded_a, axis=0) #removes 1 dimensions across specified axis position 0
print(squeezed_a)

squeezed_a = tf.squeeze(expanded_a, axis=1) #removes 1 dimensions across specified axis position 1
print(squeezed_a)

#squeeze using for loop
print("for")
for i in range(2):
  print(tf.squeeze(expanded_a, axis=0).shape) #every time it squeezes 0th axis, and the next axis would become 0th, so squeexe continues


(1, 4)
(1, 1, 4)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
for
(1, 4)
(1, 4)


### tf.reshape
  Reshapes a tensor of given shape.

  We can also reshape to perform the operation of squeeze

In [ ]:
t1 = [[1, 2, 3],
      [4, 5, 6]]

print(tf.shape(t1).numpy())

#reshape to 1D
t2 = tf.reshape(t1, [6]) #tf.reshape(t1, -1) also does the same
print(t2.shape)

#reshape to 1D using -1
t3 = tf.reshape(t1, -1)
print(t3.shape)

#reshape to 1D using -1
t3 = tf.reshape(t1, [1, -1])
print(t3.shape)

#reshape to 3D - we can reshape to higher dimension i.e 2d to 3d
#but make sure the multiplication of all elements in shape = no of total elements in the tensor
#same rule applies from higher dimension to lower dimension. Num of total elements should match with shape multiplication
# t3 = tf.reshape(t1, [4, 2, 3]) #throws error as 4*2*3 != 6
t3 = tf.reshape(t1, [1, 2, 3])
print(t3.shape)

t3 = tf.reshape(t1, [1, 1, 6])
print(t3.shape)

#2d to 4d - same rule applies
t3 = tf.reshape(t1, [1, 2, 1, 3])
print(t3.shape)

#squeeze operation, tf.reshape to achieve the same
t3 = tf.reshape(t1, [1, 2, 1, 3])
t3_sq = tf.squeeze(t3)
print(t3_sq.shape)
t3_reshape = tf.reshape(t3, [2, 3])
print(t3_reshape.shape)

[2 3]
(6,)
(6,)
(1, 6)
(1, 2, 3)
(1, 1, 6)
(1, 2, 1, 3)
(2, 3)
(2, 3)


### tf.concat

  Concatenates tensors along one dimension.

  The number of dimensions of the input tensors must match, and all dimensions except axis must be equal.

  Small shortcut is: whatever axis we specify in concat method, think of other axis as fixed, and we add the value that is there in the specified axis position of 2(or more) tensors that we are concatenating

  Note: If you are concatenating along a new axis consider using tf.stack.

  tf.concat([tf.expand_dims(t, axis) for t in mytensors], axis) can be rewritten as tf.stack(tensors, axis=axis)

In [ ]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])
print(t1.shape)
print(t2.shape)

t3_concat = tf.concat((t1, t2), axis=0) #concant along rows , vertical direction concatenation
print(t3_concat.shape)

print("\n"+str(t1.numpy()))
print(t2.numpy())
print(t3_concat.numpy())
#notice how one 2D matrix of 2rows 3 cols is added to another 2D matrix resulted in a 2D matrix of 4 rows 3 columns
#concat gives the same dimension as result like input 2D or 3D .., but the inner chnages will happen like increasing the rows or cols or channels

(2, 3)
(2, 3)
(4, 3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12]])
print(t1.shape)
print(t2.shape)

t3_concat = tf.concat((t1, t2), axis=1) #concant along columns , horizontal direction concatenation
print(t3_concat.shape)

(2, 3)
(2, 3)
(2, 6)


In [ ]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[7, 8, 9], [10, 11, 12], [-10, -11, -12]])
print(t1.shape)
print(t2.shape)

t3_concat = tf.concat((t1, t2), axis=1) #throws error as first dimension value in t1 != first dimension value in t2
print(t3_concat.shape)

(2, 3)
(3, 3)


InvalidArgumentError: ignored

In [ ]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[[7, 8, 9], [10, 11, 12]]])
print(t1.shape)
print(t2.shape)

t3_concat = tf.concat((t1, t2), axis=1) #throws error as no of dimensions are not equal 2D and 3D
print(t3_concat.shape)

(2, 3)
(1, 2, 3)


InvalidArgumentError: ignored

In [ ]:
#axis with negative number

#the axis param could also be negative numbers.
#Negative axis are interpreted as counting from the end of the rank, i.e., axis=-1 represents last axis

t1 = tf.constant([
    [[1, 2],
     [2, 3]],
     [[4, 4],
      [5, 3]]
  ])
t2 = tf.constant([
    [[7, 4],
     [8, 4]],
     [[2, 10],
      [15, 11]]])
print(t1.shape)
print(t2.shape)

tf.concat([t1, t2], -1)#concatenating at 3rd dimension - number of channels increases c in each batch

(2, 2, 2)
(2, 2, 2)


<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  7,  4],
        [ 2,  3,  8,  4]],

       [[ 4,  4,  2, 10],
        [ 5,  3, 15, 11]]], dtype=int32)>

### tf.stack
  Stacks a list of rank-R tensors into one rank-(R+1) tensor. Here rank refers to ndim

  tf.stack performs concatenation of 2 or more tensors like tf.concat but the difference between them is, tf.stack always concatenated by creating new axis for the axis that is specified in tf.stack() method for all the tensors we are trying to stack or concatenate.

  For eg, if
  - t1 shape is (2, 3)
  - t2 shape is (2, 3)
  - tf.concat([t1, t2], axis=0) concatenates across first axis and gives (4, 3) as resultant shape
  - - tf.concat([t1, t2], axis=0) creates new axis at 0th axis position for both tensors, so t1 and t2 will have shape (1, 2, 3) and then concatenates across this newly created first axis to give resultant shape (2, 2, 3). It basically keeps the shaped of matrices intact and concatenate


In [ ]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
tf.stack([x, y, z]) #each x y z will be of shape (1, 2) (1, 2) (1, 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
tf.stack([x, y, z], axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>